//! Bulk operations for Branch entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateBranchDto;
use crate::application::service::BranchService;
use crate::domain::entity::Branch;

/// Bulk operation handler for Branch entities.
///
/// Wraps `BranchService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type BranchBulkService = GenericBulkService<Branch, CreateBranchDto, BranchService>;

// <<< CUSTOM
// END CUSTOM
