//! Bulk operations for Company entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCompanyDto;
use crate::application::service::CompanyService;
use crate::domain::entity::Company;

/// Bulk operation handler for Company entities.
///
/// Wraps `CompanyService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CompanyBulkService = GenericBulkService<Company, CreateCompanyDto, CompanyService>;

// <<< CUSTOM
// END CUSTOM
