//! Bulk operations for Industry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateIndustryDto;
use crate::application::service::IndustryService;
use crate::domain::entity::Industry;

/// Bulk operation handler for Industry entities.
///
/// Wraps `IndustryService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type IndustryBulkService = GenericBulkService<Industry, CreateIndustryDto, IndustryService>;

// <<< CUSTOM
// END CUSTOM
