//! Bulk operations for Position entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreatePositionDto;
use crate::application::service::PositionService;
use crate::domain::entity::Position;

/// Bulk operation handler for Position entities.
///
/// Wraps `PositionService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type PositionBulkService = GenericBulkService<Position, CreatePositionDto, PositionService>;

// <<< CUSTOM
// END CUSTOM
