//! Bulk operations for Structure entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateStructureDto;
use crate::application::service::StructureService;
use crate::domain::entity::Structure;

/// Bulk operation handler for Structure entities.
///
/// Wraps `StructureService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type StructureBulkService = GenericBulkService<Structure, CreateStructureDto, StructureService>;

// <<< CUSTOM
// END CUSTOM
