//! Branch DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Branch;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::BranchType;
use crate::domain::entity::OrgStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Branch
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateBranchDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(alias = "branch_type")]
    pub branch_type: BranchType,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_head_office")]
    pub is_head_office: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 25)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub npwp: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub province: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "postal_code")]
    pub postal_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub country: String,
    pub status: OrgStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Branch
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateBranchDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(alias = "branch_type")]
    pub branch_type: BranchType,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_head_office")]
    pub is_head_office: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 25)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub npwp: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub province: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "postal_code")]
    pub postal_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub country: String,
    pub status: OrgStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Branch
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchBranchDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "branch_type")]
    pub branch_type: Option<BranchType>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_head_office")]
    pub is_head_office: Option<bool>,
    #[cfg_attr(feature = "validation", validate(length(max = 25)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub npwp: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub province: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "postal_code")]
    pub postal_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<OrgStatus>,
}

impl PatchBranchDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.code.is_some() || self.name.is_some() || self.branch_type.is_some() || self.is_head_office.is_some() || self.npwp.is_some() || self.email.is_some() || self.phone.is_some() || self.address.is_some() || self.city.is_some() || self.province.is_some() || self.postal_code.is_some() || self.country.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Branch entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BranchResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub branch_type: BranchType,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_head_office: bool,
    pub npwp: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub address: Option<String>,
    pub city: Option<String>,
    pub province: Option<String>,
    pub postal_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub country: String,
    pub status: OrgStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Branch entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BranchListResponseDto {
    /// List of items
    pub items: Vec<BranchResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl BranchListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<BranchResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BranchSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Branch> for BranchResponseDto {
    fn from(entity: Branch) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            code: entity.code,
            name: entity.name,
            branch_type: entity.branch_type,
            is_head_office: entity.is_head_office,
            npwp: entity.npwp,
            email: entity.email,
            phone: entity.phone,
            address: entity.address,
            city: entity.city,
            province: entity.province,
            postal_code: entity.postal_code,
            country: entity.country,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<Branch> for BranchSummaryDto {
    fn from(entity: Branch) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            code: entity.code,
            name: entity.name,
            created_at,
        }
    }
}

impl From<CreateBranchDto> for Branch {
    fn from(dto: CreateBranchDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            code: dto.code,
            name: dto.name,
            branch_type: dto.branch_type,
            is_head_office: dto.is_head_office,
            npwp: dto.npwp,
            email: dto.email,
            phone: dto.phone,
            address: dto.address,
            city: dto.city,
            province: dto.province,
            postal_code: dto.postal_code,
            country: dto.country,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Branch> for BranchResponseDto {
    fn from(entity: &Branch) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            code: entity.code.clone(),
            name: entity.name.clone(),
            branch_type: entity.branch_type.clone(),
            is_head_office: entity.is_head_office.clone(),
            npwp: entity.npwp.clone(),
            email: entity.email.clone(),
            phone: entity.phone.clone(),
            address: entity.address.clone(),
            city: entity.city.clone(),
            province: entity.province.clone(),
            postal_code: entity.postal_code.clone(),
            country: entity.country.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateBranchDto> for Branch {
    fn from_create_dto(dto: CreateBranchDto) -> backbone_core::ServiceResult<Self> {
        Ok(Branch::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateBranchDto> for Branch {
    fn apply_update(mut self, dto: UpdateBranchDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.code = dto.code;
        self.name = dto.name;
        self.branch_type = dto.branch_type;
        self.is_head_office = dto.is_head_office;
        self.npwp = dto.npwp;
        self.email = dto.email;
        self.phone = dto.phone;
        self.address = dto.address;
        self.city = dto.city;
        self.province = dto.province;
        self.postal_code = dto.postal_code;
        self.country = dto.country;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Branch here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
