//! CompanyIndustry DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::CompanyIndustry;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new CompanyIndustry
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCompanyIndustryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "industry_id")]
    pub industry_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_primary")]
    pub is_primary: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a CompanyIndustry
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCompanyIndustryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "industry_id")]
    pub industry_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_primary")]
    pub is_primary: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a CompanyIndustry
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCompanyIndustryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "industry_id")]
    pub industry_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_primary")]
    pub is_primary: Option<bool>,
}

impl PatchCompanyIndustryDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.industry_id.is_some() || self.is_primary.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for CompanyIndustry entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CompanyIndustryResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub industry_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_primary: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for CompanyIndustry entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CompanyIndustryListResponseDto {
    /// List of items
    pub items: Vec<CompanyIndustryResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CompanyIndustryListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CompanyIndustryResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CompanyIndustrySummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub industry_id: Uuid,
    pub is_primary: bool,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<CompanyIndustry> for CompanyIndustryResponseDto {
    fn from(entity: CompanyIndustry) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            industry_id: entity.industry_id,
            is_primary: entity.is_primary,
            metadata: entity.metadata,
        }
    }
}

impl From<CompanyIndustry> for CompanyIndustrySummaryDto {
    fn from(entity: CompanyIndustry) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            industry_id: entity.industry_id,
            is_primary: entity.is_primary,
            created_at,
        }
    }
}

impl From<CreateCompanyIndustryDto> for CompanyIndustry {
    fn from(dto: CreateCompanyIndustryDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            industry_id: dto.industry_id,
            is_primary: dto.is_primary,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&CompanyIndustry> for CompanyIndustryResponseDto {
    fn from(entity: &CompanyIndustry) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            industry_id: entity.industry_id.clone(),
            is_primary: entity.is_primary.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCompanyIndustryDto> for CompanyIndustry {
    fn from_create_dto(dto: CreateCompanyIndustryDto) -> backbone_core::ServiceResult<Self> {
        Ok(CompanyIndustry::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCompanyIndustryDto> for CompanyIndustry {
    fn apply_update(mut self, dto: UpdateCompanyIndustryDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.industry_id = dto.industry_id;
        self.is_primary = dto.is_primary;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to CompanyIndustry here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
