//! Company DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Company;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::CompanyEntityType;
use crate::domain::entity::CompanyStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Company
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCompanyDto {
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "legal_name")]
    pub legal_name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "trade_name")]
    pub trade_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 25)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub npwp: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nib: Option<String>,
    #[serde(alias = "entity_type")]
    pub entity_type: CompanyEntityType,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "base_currency")]
    pub base_currency: String,
    #[cfg_attr(feature = "validation", validate(range(min = 1), range(max = 12)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "fiscal_year_start_month")]
    pub fiscal_year_start_month: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub province: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "postal_code")]
    pub postal_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub country: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parent_company_id")]
    pub parent_company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_default")]
    pub is_default: bool,
    pub status: CompanyStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Company
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCompanyDto {
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "legal_name")]
    pub legal_name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "trade_name")]
    pub trade_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 25)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub npwp: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nib: Option<String>,
    #[serde(alias = "entity_type")]
    pub entity_type: CompanyEntityType,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "base_currency")]
    pub base_currency: String,
    #[cfg_attr(feature = "validation", validate(range(min = 1), range(max = 12)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "fiscal_year_start_month")]
    pub fiscal_year_start_month: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub province: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "postal_code")]
    pub postal_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub country: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parent_company_id")]
    pub parent_company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_default")]
    pub is_default: bool,
    pub status: CompanyStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Company
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCompanyDto {
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "legal_name")]
    pub legal_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "trade_name")]
    pub trade_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 25)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub npwp: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nib: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "entity_type")]
    pub entity_type: Option<CompanyEntityType>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "base_currency")]
    pub base_currency: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(min = 1), range(max = 12)))]
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "fiscal_year_start_month")]
    pub fiscal_year_start_month: Option<i32>,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub province: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "postal_code")]
    pub postal_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "parent_company_id")]
    pub parent_company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_default")]
    pub is_default: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<CompanyStatus>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl PatchCompanyDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.code.is_some() || self.legal_name.is_some() || self.trade_name.is_some() || self.npwp.is_some() || self.nib.is_some() || self.entity_type.is_some() || self.base_currency.is_some() || self.fiscal_year_start_month.is_some() || self.email.is_some() || self.phone.is_some() || self.address.is_some() || self.city.is_some() || self.province.is_some() || self.postal_code.is_some() || self.country.is_some() || self.parent_company_id.is_some() || self.is_default.is_some() || self.status.is_some() || self.notes.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Company entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CompanyResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub legal_name: String,
    pub trade_name: Option<String>,
    pub npwp: Option<String>,
    pub nib: Option<String>,
    pub entity_type: CompanyEntityType,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub base_currency: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub fiscal_year_start_month: i32,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub address: Option<String>,
    pub city: Option<String>,
    pub province: Option<String>,
    pub postal_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub country: String,
    pub parent_company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_default: bool,
    pub status: CompanyStatus,
    pub notes: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Company entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CompanyListResponseDto {
    /// List of items
    pub items: Vec<CompanyResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CompanyListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CompanyResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CompanySummaryDto {
    pub id: Uuid,
    pub code: String,
    pub legal_name: String,
    pub trade_name: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Company> for CompanyResponseDto {
    fn from(entity: Company) -> Self {
        Self {
            id: entity.id,
            code: entity.code,
            legal_name: entity.legal_name,
            trade_name: entity.trade_name,
            npwp: entity.npwp,
            nib: entity.nib,
            entity_type: entity.entity_type,
            base_currency: entity.base_currency,
            fiscal_year_start_month: entity.fiscal_year_start_month,
            email: entity.email,
            phone: entity.phone,
            address: entity.address,
            city: entity.city,
            province: entity.province,
            postal_code: entity.postal_code,
            country: entity.country,
            parent_company_id: entity.parent_company_id,
            is_default: entity.is_default,
            status: entity.status,
            notes: entity.notes,
            metadata: entity.metadata,
        }
    }
}

impl From<Company> for CompanySummaryDto {
    fn from(entity: Company) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            code: entity.code,
            legal_name: entity.legal_name,
            trade_name: entity.trade_name,
            created_at,
        }
    }
}

impl From<CreateCompanyDto> for Company {
    fn from(dto: CreateCompanyDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            code: dto.code,
            legal_name: dto.legal_name,
            trade_name: dto.trade_name,
            npwp: dto.npwp,
            nib: dto.nib,
            entity_type: dto.entity_type,
            base_currency: dto.base_currency,
            fiscal_year_start_month: dto.fiscal_year_start_month,
            email: dto.email,
            phone: dto.phone,
            address: dto.address,
            city: dto.city,
            province: dto.province,
            postal_code: dto.postal_code,
            country: dto.country,
            parent_company_id: dto.parent_company_id,
            is_default: dto.is_default,
            status: dto.status,
            notes: dto.notes,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Company> for CompanyResponseDto {
    fn from(entity: &Company) -> Self {
        Self {
            id: entity.id.clone(),
            code: entity.code.clone(),
            legal_name: entity.legal_name.clone(),
            trade_name: entity.trade_name.clone(),
            npwp: entity.npwp.clone(),
            nib: entity.nib.clone(),
            entity_type: entity.entity_type.clone(),
            base_currency: entity.base_currency.clone(),
            fiscal_year_start_month: entity.fiscal_year_start_month.clone(),
            email: entity.email.clone(),
            phone: entity.phone.clone(),
            address: entity.address.clone(),
            city: entity.city.clone(),
            province: entity.province.clone(),
            postal_code: entity.postal_code.clone(),
            country: entity.country.clone(),
            parent_company_id: entity.parent_company_id.clone(),
            is_default: entity.is_default.clone(),
            status: entity.status.clone(),
            notes: entity.notes.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCompanyDto> for Company {
    fn from_create_dto(dto: CreateCompanyDto) -> backbone_core::ServiceResult<Self> {
        Ok(Company::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCompanyDto> for Company {
    fn apply_update(mut self, dto: UpdateCompanyDto) -> backbone_core::ServiceResult<Self> {
        self.code = dto.code;
        self.legal_name = dto.legal_name;
        self.trade_name = dto.trade_name;
        self.npwp = dto.npwp;
        self.nib = dto.nib;
        self.entity_type = dto.entity_type;
        self.base_currency = dto.base_currency;
        self.fiscal_year_start_month = dto.fiscal_year_start_month;
        self.email = dto.email;
        self.phone = dto.phone;
        self.address = dto.address;
        self.city = dto.city;
        self.province = dto.province;
        self.postal_code = dto.postal_code;
        self.country = dto.country;
        self.parent_company_id = dto.parent_company_id;
        self.is_default = dto.is_default;
        self.status = dto.status;
        self.notes = dto.notes;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Company here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
