//! Department DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Department;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::OrgStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Department
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateDepartmentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parent_id")]
    pub parent_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub level: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_group")]
    pub is_group: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "manager_id")]
    pub manager_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "sort_order")]
    pub sort_order: i32,
    pub status: OrgStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Department
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateDepartmentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parent_id")]
    pub parent_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub level: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_group")]
    pub is_group: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "manager_id")]
    pub manager_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "sort_order")]
    pub sort_order: i32,
    pub status: OrgStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Department
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchDepartmentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "parent_id")]
    pub parent_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub level: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_group")]
    pub is_group: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "manager_id")]
    pub manager_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "sort_order")]
    pub sort_order: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<OrgStatus>,
}

impl PatchDepartmentDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.code.is_some() || self.name.is_some() || self.parent_id.is_some() || self.level.is_some() || self.is_group.is_some() || self.branch_id.is_some() || self.manager_id.is_some() || self.sort_order.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Department entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DepartmentResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub parent_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub level: i32,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_group: bool,
    pub branch_id: Option<Uuid>,
    pub manager_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sort_order: i32,
    pub status: OrgStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Department entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DepartmentListResponseDto {
    /// List of items
    pub items: Vec<DepartmentResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl DepartmentListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<DepartmentResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DepartmentSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Department> for DepartmentResponseDto {
    fn from(entity: Department) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            code: entity.code,
            name: entity.name,
            parent_id: entity.parent_id,
            level: entity.level,
            is_group: entity.is_group,
            branch_id: entity.branch_id,
            manager_id: entity.manager_id,
            sort_order: entity.sort_order,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<Department> for DepartmentSummaryDto {
    fn from(entity: Department) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            code: entity.code,
            name: entity.name,
            created_at,
        }
    }
}

impl From<CreateDepartmentDto> for Department {
    fn from(dto: CreateDepartmentDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            code: dto.code,
            name: dto.name,
            parent_id: dto.parent_id,
            level: dto.level,
            is_group: dto.is_group,
            branch_id: dto.branch_id,
            manager_id: dto.manager_id,
            sort_order: dto.sort_order,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Department> for DepartmentResponseDto {
    fn from(entity: &Department) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            code: entity.code.clone(),
            name: entity.name.clone(),
            parent_id: entity.parent_id.clone(),
            level: entity.level.clone(),
            is_group: entity.is_group.clone(),
            branch_id: entity.branch_id.clone(),
            manager_id: entity.manager_id.clone(),
            sort_order: entity.sort_order.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateDepartmentDto> for Department {
    fn from_create_dto(dto: CreateDepartmentDto) -> backbone_core::ServiceResult<Self> {
        Ok(Department::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateDepartmentDto> for Department {
    fn apply_update(mut self, dto: UpdateDepartmentDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.code = dto.code;
        self.name = dto.name;
        self.parent_id = dto.parent_id;
        self.level = dto.level;
        self.is_group = dto.is_group;
        self.branch_id = dto.branch_id;
        self.manager_id = dto.manager_id;
        self.sort_order = dto.sort_order;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Department here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
