//! OrgUnit DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::OrgUnit;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::OrgUnitKind;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new OrgUnit
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateOrgUnitDto {
    pub kind: OrgUnitKind,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parent_id")]
    pub parent_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a OrgUnit
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateOrgUnitDto {
    pub kind: OrgUnitKind,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parent_id")]
    pub parent_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a OrgUnit
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchOrgUnitDto {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kind: Option<OrgUnitKind>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "parent_id")]
    pub parent_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl PatchOrgUnitDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.kind.is_some() || self.parent_id.is_some() || self.code.is_some() || self.name.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for OrgUnit entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrgUnitResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    pub kind: OrgUnitKind,
    pub parent_id: Option<Uuid>,
    pub code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for OrgUnit entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrgUnitListResponseDto {
    /// List of items
    pub items: Vec<OrgUnitResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl OrgUnitListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<OrgUnitResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OrgUnitSummaryDto {
    pub id: Uuid,
    pub kind: OrgUnitKind,
    pub parent_id: Option<Uuid>,
    pub code: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<OrgUnit> for OrgUnitResponseDto {
    fn from(entity: OrgUnit) -> Self {
        Self {
            id: entity.id,
            kind: entity.kind,
            parent_id: entity.parent_id,
            code: entity.code,
            name: entity.name,
            metadata: entity.metadata,
        }
    }
}

impl From<OrgUnit> for OrgUnitSummaryDto {
    fn from(entity: OrgUnit) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            kind: entity.kind,
            parent_id: entity.parent_id,
            code: entity.code,
            created_at,
        }
    }
}

impl From<CreateOrgUnitDto> for OrgUnit {
    fn from(dto: CreateOrgUnitDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            kind: dto.kind,
            parent_id: dto.parent_id,
            code: dto.code,
            name: dto.name,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&OrgUnit> for OrgUnitResponseDto {
    fn from(entity: &OrgUnit) -> Self {
        Self {
            id: entity.id.clone(),
            kind: entity.kind.clone(),
            parent_id: entity.parent_id.clone(),
            code: entity.code.clone(),
            name: entity.name.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateOrgUnitDto> for OrgUnit {
    fn from_create_dto(dto: CreateOrgUnitDto) -> backbone_core::ServiceResult<Self> {
        Ok(OrgUnit::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateOrgUnitDto> for OrgUnit {
    fn apply_update(mut self, dto: UpdateOrgUnitDto) -> backbone_core::ServiceResult<Self> {
        self.kind = dto.kind;
        self.parent_id = dto.parent_id;
        self.code = dto.code;
        self.name = dto.name;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to OrgUnit here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
