//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod branch_specification;
pub mod company_specification;
pub mod company_industry_specification;
pub mod department_specification;
pub mod industry_specification;

// <<< CUSTOM
// END CUSTOM
