//! Domain policy for Level aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Level;

/// Domain policy for Level — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Level>` in the `// <<< CUSTOM` zone.
pub type LevelDomainPolicy = PermitAllPolicy<Level>;

// <<< CUSTOM
// END CUSTOM
