//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod branch_domain_policy;
pub mod company_domain_policy;
pub mod department_domain_policy;

pub use branch_domain_policy::BranchDomainPolicy;
pub use company_domain_policy::CompanyDomainPolicy;
pub use department_domain_policy::DepartmentDomainPolicy;

// <<< CUSTOM
// END CUSTOM
