//! Domain policy for Position aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Position;

/// Domain policy for Position — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Position>` in the `// <<< CUSTOM` zone.
pub type PositionDomainPolicy = PermitAllPolicy<Position>;

// <<< CUSTOM
// END CUSTOM
