//! Domain policy for Structure aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Structure;

/// Domain policy for Structure — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Structure>` in the `// <<< CUSTOM` zone.
pub type StructureDomainPolicy = PermitAllPolicy<Structure>;

// <<< CUSTOM
// END CUSTOM
