//! Application service for Branch entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `branch_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateBranchDto, UpdateBranchDto};
use crate::domain::entity::Branch;
use crate::infrastructure::persistence::BranchRepository;

/// Application service for Branch entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `branch_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct BranchServiceCustom {
///     inner: Arc<BranchService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type BranchService = GenericCrudService<
    Branch,
    CreateBranchDto,
    UpdateBranchDto,
    BranchRepository,
>;

// <<< CUSTOM
// END CUSTOM
