//! Application service for CompanyIndustry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `company_industry_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCompanyIndustryDto, UpdateCompanyIndustryDto};
use crate::domain::entity::CompanyIndustry;
use crate::infrastructure::persistence::CompanyIndustryRepository;

/// Application service for CompanyIndustry entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `company_industry_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CompanyIndustryServiceCustom {
///     inner: Arc<CompanyIndustryService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CompanyIndustryService = GenericCrudService<
    CompanyIndustry,
    CreateCompanyIndustryDto,
    UpdateCompanyIndustryDto,
    CompanyIndustryRepository,
>;

// <<< CUSTOM
// END CUSTOM
