//! Application service for Company entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `company_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCompanyDto, UpdateCompanyDto};
use crate::domain::entity::Company;
use crate::infrastructure::persistence::CompanyRepository;

/// Application service for Company entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `company_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CompanyServiceCustom {
///     inner: Arc<CompanyService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CompanyService = GenericCrudService<
    Company,
    CreateCompanyDto,
    UpdateCompanyDto,
    CompanyRepository,
>;

// <<< CUSTOM
// END CUSTOM
