//! Application service for Department entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `department_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateDepartmentDto, UpdateDepartmentDto};
use crate::domain::entity::Department;
use crate::infrastructure::persistence::DepartmentRepository;

/// Application service for Department entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `department_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct DepartmentServiceCustom {
///     inner: Arc<DepartmentService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type DepartmentService = GenericCrudService<
    Department,
    CreateDepartmentDto,
    UpdateDepartmentDto,
    DepartmentRepository,
>;

// <<< CUSTOM
// END CUSTOM
