//! Application service for Level entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `level_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateLevelDto, UpdateLevelDto};
use crate::domain::entity::Level;
use crate::infrastructure::persistence::LevelRepository;

/// Application service for Level entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `level_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct LevelServiceCustom {
///     inner: Arc<LevelService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type LevelService = GenericCrudService<
    Level,
    CreateLevelDto,
    UpdateLevelDto,
    LevelRepository,
>;

// <<< CUSTOM
// END CUSTOM
