//! Application service for OrgUnit entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `org_unit_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateOrgUnitDto, UpdateOrgUnitDto};
use crate::domain::entity::OrgUnit;
use crate::infrastructure::persistence::OrgUnitRepository;

/// Application service for OrgUnit entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `org_unit_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct OrgUnitServiceCustom {
///     inner: Arc<OrgUnitService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type OrgUnitService = GenericCrudService<
    OrgUnit,
    CreateOrgUnitDto,
    UpdateOrgUnitDto,
    OrgUnitRepository,
>;

// <<< CUSTOM
// END CUSTOM
