//! Application service for Position entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `position_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePositionDto, UpdatePositionDto};
use crate::domain::entity::Position;
use crate::infrastructure::persistence::PositionRepository;

/// Application service for Position entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `position_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PositionServiceCustom {
///     inner: Arc<PositionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PositionService = GenericCrudService<
    Position,
    CreatePositionDto,
    UpdatePositionDto,
    PositionRepository,
>;

// <<< CUSTOM
// END CUSTOM
