//! Application service for Structure entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `structure_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateStructureDto, UpdateStructureDto};
use crate::domain::entity::Structure;
use crate::infrastructure::persistence::StructureRepository;

/// Application service for Structure entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `structure_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct StructureServiceCustom {
///     inner: Arc<StructureService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type StructureService = GenericCrudService<
    Structure,
    CreateStructureDto,
    UpdateStructureDto,
    StructureRepository,
>;

// <<< CUSTOM
// END CUSTOM
