-- CompanyIndustry Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the organization.company_industries table.
-- Customize this file to add your initial data.

-- INSERT INTO organization.company_industries (
--     id,
--     company_id,
--     industry_id,
--     is_primary,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO organization.company_industries (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

-- Add custom seed data below (typically none — links are created via the API).