-- Company Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the organization.companies table.
-- Customize this file to add your initial data.

-- INSERT INTO organization.companies (
--     id,
--     code,
--     legal_name,
--     trade_name,
--     npwp,
--     nib,
--     entity_type,
--     base_currency,
--     fiscal_year_start_month,
--     email,
--     phone,
--     address,
--     city,
--     province,
--     postal_code,
--     country,
--     parent_company_id,
--     is_default,
--     status,
--     notes,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO organization.companies (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

