-- SEED: none
--
-- A company's departments are its own structure — its divisions, their nesting and
-- their managers. There is no industry-standard department list that would be
-- right for the next tenant, and shipping a guess would have every company
-- delete rows before it could add its real ones.
--
-- The tenancy descriptor anchors this table on a company or branch node, which
-- is the same statement in schema form: there is no tenant-independent row to
-- seed, and a seed run has no company to anchor one to.
