-- Industry Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the organization.industries table.
-- Customize this file to add your initial data.

-- INSERT INTO organization.industries (
--     id,
--     code,
--     name,
--     sector,
--     parent_id,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

INSERT INTO organization.industries (id, code, name, description, is_active, sort_order, created_at, updated_at) VALUES
    (gen_random_uuid(), 'TECH', 'Technology', 'Information technology and software', true, 1, NOW(), NOW()),
    (gen_random_uuid(), 'FIN', 'Financial Services', 'Banking, insurance, and financial services', true, 2, NOW(), NOW()),
    (gen_random_uuid(), 'HEALTH', 'Healthcare', 'Healthcare and medical services', true, 3, NOW(), NOW()),
    (gen_random_uuid(), 'EDU', 'Education', 'Educational institutions and services', true, 4, NOW(), NOW()),
    (gen_random_uuid(), 'MFG', 'Manufacturing', 'Manufacturing and production', true, 5, NOW(), NOW()),
    (gen_random_uuid(), 'RETAIL', 'Retail', 'Retail and consumer goods', true, 6, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

