-- SEED: none
--
-- Job positions are a company's own ladder. Titles, grades and their meaning differ
-- between organisations of the same size in the same industry.
--
-- The tenancy descriptor anchors this table on a company or branch node, which
-- is the same statement in schema form: there is no tenant-independent row to
-- seed, and a seed run has no company to anchor one to.
