-- Migration: Create positions table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS organization;

CREATE TABLE IF NOT EXISTS organization.positions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    code TEXT,
    description TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_positions_company_id_code ON organization.positions (company_id, code) WHERE code IS NOT NULL AND (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_positions_company_id_name ON organization.positions (company_id, name);

CREATE INDEX IF NOT EXISTS idx_positions_company_id ON organization.positions (company_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_positions_metadata_gin ON organization.positions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_positions_metadata_deleted_at ON organization.positions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_positions_metadata_created_at ON organization.positions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_positions_metadata_updated_at ON organization.positions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION organization.positions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS positions_insert_audit ON organization.positions;
CREATE TRIGGER positions_insert_audit BEFORE INSERT ON organization.positions
    FOR EACH ROW EXECUTE FUNCTION organization.positions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS positions_update_audit ON organization.positions;
CREATE TRIGGER positions_update_audit BEFORE UPDATE ON organization.positions
    FOR EACH ROW EXECUTE FUNCTION organization.positions_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE organization.positions ADD CONSTRAINT fk_positions_company_id FOREIGN KEY (company_id) REFERENCES organization.companies (id);
