-- Migration: Create company_industries table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS organization;

CREATE TABLE IF NOT EXISTS organization.company_industries (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    industry_id UUID NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_company_industries_company_id_industry_id ON organization.company_industries (company_id, industry_id) WHERE (metadata->>'deleted_at') IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_company_industries_company_id ON organization.company_industries (company_id) WHERE is_primary = true AND (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_company_industries_company_id_is_primary ON organization.company_industries (company_id, is_primary);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_company_industries_metadata_gin ON organization.company_industries USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_company_industries_metadata_deleted_at ON organization.company_industries ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_company_industries_metadata_created_at ON organization.company_industries ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_company_industries_metadata_updated_at ON organization.company_industries ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION organization.company_industries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS company_industries_insert_audit ON organization.company_industries;
CREATE TRIGGER company_industries_insert_audit BEFORE INSERT ON organization.company_industries
    FOR EACH ROW EXECUTE FUNCTION organization.company_industries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS company_industries_update_audit ON organization.company_industries;
CREATE TRIGGER company_industries_update_audit BEFORE UPDATE ON organization.company_industries
    FOR EACH ROW EXECUTE FUNCTION organization.company_industries_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE organization.company_industries ADD CONSTRAINT fk_company_industries_company_id FOREIGN KEY (company_id) REFERENCES organization.companies (id);
ALTER TABLE organization.company_industries ADD CONSTRAINT fk_company_industries_industry_id FOREIGN KEY (industry_id) REFERENCES organization.industries (id);
