-- Migration: Create industries table
-- Generated by metaphor-schema

-- Create kbli_sector enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'kbli_sector') THEN
        CREATE TYPE kbli_sector AS ENUM ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u');
    END IF;
END
$$;

-- Create org_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'org_status') THEN
        CREATE TYPE org_status AS ENUM ('active', 'inactive');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS organization;

CREATE TABLE IF NOT EXISTS organization.industries (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    sector kbli_sector NOT NULL,
    parent_id UUID,
    status org_status NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_industries_code ON organization.industries (code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_industries_sector ON organization.industries (sector);

CREATE INDEX IF NOT EXISTS idx_industries_parent_id ON organization.industries (parent_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_industries_metadata_gin ON organization.industries USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_industries_metadata_deleted_at ON organization.industries ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_industries_metadata_created_at ON organization.industries ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_industries_metadata_updated_at ON organization.industries ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION organization.industries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS industries_insert_audit ON organization.industries;
CREATE TRIGGER industries_insert_audit BEFORE INSERT ON organization.industries
    FOR EACH ROW EXECUTE FUNCTION organization.industries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS industries_update_audit ON organization.industries;
CREATE TRIGGER industries_update_audit BEFORE UPDATE ON organization.industries
    FOR EACH ROW EXECUTE FUNCTION organization.industries_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE organization.industries ADD CONSTRAINT fk_industries_parent_id FOREIGN KEY (parent_id) REFERENCES organization.industries (id);
