-- Migration: Create branches table
-- Generated by metaphor-schema

-- Create branch_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'branch_type') THEN
        CREATE TYPE branch_type AS ENUM ('head_office', 'branch', 'warehouse', 'outlet', 'factory');
    END IF;
END
$$;

-- Create org_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'org_status') THEN
        CREATE TYPE org_status AS ENUM ('active', 'inactive');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS organization;

CREATE TABLE IF NOT EXISTS organization.branches (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    branch_type branch_type NOT NULL DEFAULT 'branch',
    is_head_office BOOLEAN NOT NULL DEFAULT FALSE,
    npwp TEXT,
    email TEXT,
    phone TEXT,
    address TEXT,
    city TEXT,
    province TEXT,
    postal_code TEXT,
    country TEXT NOT NULL DEFAULT 'ID',
    status org_status NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_branches_company_id_code ON organization.branches (company_id, code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_branches_company_id_status ON organization.branches (company_id, status);

CREATE INDEX IF NOT EXISTS idx_branches_company_id_is_head_office ON organization.branches (company_id, is_head_office);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_branches_metadata_gin ON organization.branches USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_branches_metadata_deleted_at ON organization.branches ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_branches_metadata_created_at ON organization.branches ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_branches_metadata_updated_at ON organization.branches ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION organization.branches_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS branches_insert_audit ON organization.branches;
CREATE TRIGGER branches_insert_audit BEFORE INSERT ON organization.branches
    FOR EACH ROW EXECUTE FUNCTION organization.branches_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS branches_update_audit ON organization.branches;
CREATE TRIGGER branches_update_audit BEFORE UPDATE ON organization.branches
    FOR EACH ROW EXECUTE FUNCTION organization.branches_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE organization.branches ADD CONSTRAINT fk_branches_company_id FOREIGN KEY (company_id) REFERENCES organization.companies (id);
