-- Company fence posture flip for organization module (ADR-0014: strict -> shared_tree)
-- Generated by metaphor-schema. A session rooted at a company now sees this module's
-- rows for the company's whole SUBTREE (organization.company_subtree over
-- companies(parent_company_id)), not just its own company_id — multi-company groups
-- are the norm (recurring-themes C2/C3). companies/industries carry no company_id
-- and stay intentionally unfenced. Also closes the unfenced gap on levels/
-- positions/structures, which shipped company_id without a policy.
-- Requires the app to connect as a non-superuser role; migrations/seeders run as
-- the owner and bypass.

-- Company subtree helper (ADR-0014 shared_tree fence).
-- Root-inclusive closure over organization.companies(parent_company_id);
-- company_subtree(NULL) returns no rows (fail-closed).
CREATE OR REPLACE FUNCTION organization.company_subtree(root uuid)
RETURNS TABLE (company_id uuid)
LANGUAGE sql
STABLE
AS $$
    WITH RECURSIVE tree AS (
        SELECT c.id AS node_id
        FROM organization.companies c
        WHERE c.id = root
        UNION ALL
        SELECT c.id
        FROM organization.companies c
        JOIN tree t ON c.parent_company_id = t.node_id
    )
    SELECT node_id FROM tree
$$;

-- Migration: company row-level-security fence for organization.branches
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE organization.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization.branches FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS branches_company_isolation ON organization.branches;
CREATE POLICY branches_company_isolation ON organization.branches
    FOR ALL
    USING      (company_id IN (SELECT company_id FROM organization.company_subtree(NULLIF(current_setting('app.company_id', true), '')::uuid)))
    WITH CHECK (company_id IN (SELECT company_id FROM organization.company_subtree(NULLIF(current_setting('app.company_id', true), '')::uuid)));

-- Migration: company row-level-security fence for organization.departments
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE organization.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization.departments FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS departments_company_isolation ON organization.departments;
CREATE POLICY departments_company_isolation ON organization.departments
    FOR ALL
    USING      (company_id IN (SELECT company_id FROM organization.company_subtree(NULLIF(current_setting('app.company_id', true), '')::uuid)))
    WITH CHECK (company_id IN (SELECT company_id FROM organization.company_subtree(NULLIF(current_setting('app.company_id', true), '')::uuid)));

-- Migration: company row-level-security fence for organization.company_industries
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE organization.company_industries ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization.company_industries FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS company_industries_company_isolation ON organization.company_industries;
CREATE POLICY company_industries_company_isolation ON organization.company_industries
    FOR ALL
    USING      (company_id IN (SELECT company_id FROM organization.company_subtree(NULLIF(current_setting('app.company_id', true), '')::uuid)))
    WITH CHECK (company_id IN (SELECT company_id FROM organization.company_subtree(NULLIF(current_setting('app.company_id', true), '')::uuid)));

-- Migration: company row-level-security fence for organization.levels
-- Generated by metaphor-schema (ADR-0014). Newly fenced: shipped with company_id
-- but no policy (the ADR-0014 sweep's first catch).

ALTER TABLE organization.levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization.levels FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS levels_company_isolation ON organization.levels;
CREATE POLICY levels_company_isolation ON organization.levels
    FOR ALL
    USING      (company_id IN (SELECT company_id FROM organization.company_subtree(NULLIF(current_setting('app.company_id', true), '')::uuid)))
    WITH CHECK (company_id IN (SELECT company_id FROM organization.company_subtree(NULLIF(current_setting('app.company_id', true), '')::uuid)));

-- Migration: company row-level-security fence for organization.positions
-- Generated by metaphor-schema (ADR-0014). Newly fenced: shipped with company_id
-- but no policy (the ADR-0014 sweep's first catch).

ALTER TABLE organization.positions ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization.positions FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS positions_company_isolation ON organization.positions;
CREATE POLICY positions_company_isolation ON organization.positions
    FOR ALL
    USING      (company_id IN (SELECT company_id FROM organization.company_subtree(NULLIF(current_setting('app.company_id', true), '')::uuid)))
    WITH CHECK (company_id IN (SELECT company_id FROM organization.company_subtree(NULLIF(current_setting('app.company_id', true), '')::uuid)));

-- Migration: company row-level-security fence for organization.structures
-- Generated by metaphor-schema (ADR-0014). Newly fenced: shipped with company_id
-- but no policy (the ADR-0014 sweep's first catch).

ALTER TABLE organization.structures ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization.structures FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS structures_company_isolation ON organization.structures;
CREATE POLICY structures_company_isolation ON organization.structures
    FOR ALL
    USING      (company_id IN (SELECT company_id FROM organization.company_subtree(NULLIF(current_setting('app.company_id', true), '')::uuid)))
    WITH CHECK (company_id IN (SELECT company_id FROM organization.company_subtree(NULLIF(current_setting('app.company_id', true), '')::uuid)));
