-- Company RLS fence for organization module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.
--
-- Tables created after this migration's date (company_industries, and the
-- July reference masters) are fenced by the migration that created them /
-- company_fence_shared_tree — NOT here. Referencing a table here breaks
-- every fresh database: this migration runs before the table exists.

-- Migration: company row-level-security fence for organization.branches
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE organization.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization.branches FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS branches_company_isolation ON organization.branches;
CREATE POLICY branches_company_isolation ON organization.branches
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for organization.departments
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE organization.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization.departments FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS departments_company_isolation ON organization.departments;
CREATE POLICY departments_company_isolation ON organization.departments
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

