-- Migration: Create departments table
-- Generated by metaphor-schema

-- Create org_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'org_status') THEN
        CREATE TYPE org_status AS ENUM ('active', 'inactive');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS organization;

CREATE TABLE IF NOT EXISTS organization.departments (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    parent_id UUID,
    level INTEGER NOT NULL DEFAULT 0,
    is_group BOOLEAN NOT NULL DEFAULT FALSE,
    branch_id UUID,
    manager_id UUID,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status org_status NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_departments_company_id_code ON organization.departments (company_id, code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_departments_company_id_parent_id_sort_order ON organization.departments (company_id, parent_id, sort_order);

CREATE INDEX IF NOT EXISTS idx_departments_company_id_status ON organization.departments (company_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_departments_metadata_gin ON organization.departments USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_departments_metadata_deleted_at ON organization.departments ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_departments_metadata_created_at ON organization.departments ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_departments_metadata_updated_at ON organization.departments ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION organization.departments_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS departments_insert_audit ON organization.departments;
CREATE TRIGGER departments_insert_audit BEFORE INSERT ON organization.departments
    FOR EACH ROW EXECUTE FUNCTION organization.departments_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS departments_update_audit ON organization.departments;
CREATE TRIGGER departments_update_audit BEFORE UPDATE ON organization.departments
    FOR EACH ROW EXECUTE FUNCTION organization.departments_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE organization.departments ADD CONSTRAINT fk_departments_company_id FOREIGN KEY (company_id) REFERENCES organization.companies (id);
ALTER TABLE organization.departments ADD CONSTRAINT fk_departments_parent_id FOREIGN KEY (parent_id) REFERENCES organization.departments (id);
ALTER TABLE organization.departments ADD CONSTRAINT fk_departments_branch_id FOREIGN KEY (branch_id) REFERENCES organization.branches (id);
