-- Migration: Create structures table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS organization;

CREATE TABLE IF NOT EXISTS organization.structures (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    parent_id UUID,
    manager_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_structures_company_id_parent_id ON organization.structures (company_id, parent_id);

CREATE INDEX IF NOT EXISTS idx_structures_company_id_name ON organization.structures (company_id, name);

CREATE INDEX IF NOT EXISTS idx_structures_parent_id ON organization.structures (parent_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_structures_metadata_gin ON organization.structures USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_structures_metadata_deleted_at ON organization.structures ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_structures_metadata_created_at ON organization.structures ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_structures_metadata_updated_at ON organization.structures ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION organization.structures_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS structures_insert_audit ON organization.structures;
CREATE TRIGGER structures_insert_audit BEFORE INSERT ON organization.structures
    FOR EACH ROW EXECUTE FUNCTION organization.structures_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS structures_update_audit ON organization.structures;
CREATE TRIGGER structures_update_audit BEFORE UPDATE ON organization.structures
    FOR EACH ROW EXECUTE FUNCTION organization.structures_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE organization.structures ADD CONSTRAINT fk_structures_company_id FOREIGN KEY (company_id) REFERENCES organization.companies (id);
ALTER TABLE organization.structures ADD CONSTRAINT fk_structures_parent_id FOREIGN KEY (parent_id) REFERENCES organization.structures (id);
