-- Company RLS fence for organization module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for organization.branches
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE organization.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization.branches FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS branches_company_isolation ON organization.branches;
CREATE POLICY branches_company_isolation ON organization.branches
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for organization.company_industries
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE organization.company_industries ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization.company_industries FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS company_industries_company_isolation ON organization.company_industries;
CREATE POLICY company_industries_company_isolation ON organization.company_industries
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for organization.departments
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE organization.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization.departments FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS departments_company_isolation ON organization.departments;
CREATE POLICY departments_company_isolation ON organization.departments
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

