-- Migration: Create companies table
-- Generated by metaphor-schema

-- Create company_entity_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'company_entity_type') THEN
        CREATE TYPE company_entity_type AS ENUM ('pt', 'cv', 'firma', 'perorangan', 'koperasi', 'yayasan', 'bumn', 'other');
    END IF;
END
$$;

-- Create company_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'company_status') THEN
        CREATE TYPE company_status AS ENUM ('active', 'inactive', 'suspended', 'dissolved');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS organization;

CREATE TABLE IF NOT EXISTS organization.companies (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    code TEXT NOT NULL,
    legal_name TEXT NOT NULL,
    trade_name TEXT,
    npwp TEXT,
    nib TEXT,
    entity_type company_entity_type NOT NULL DEFAULT 'pt',
    base_currency TEXT NOT NULL DEFAULT 'IDR',
    fiscal_year_start_month INTEGER NOT NULL DEFAULT 1,
    email TEXT,
    phone TEXT,
    address TEXT,
    city TEXT,
    province TEXT,
    postal_code TEXT,
    country TEXT NOT NULL DEFAULT 'ID',
    parent_company_id UUID,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    status company_status NOT NULL DEFAULT 'active',
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_companies_code ON organization.companies (code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_companies_npwp ON organization.companies (npwp) WHERE npwp IS NOT NULL AND (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_companies_status ON organization.companies (status);

CREATE INDEX IF NOT EXISTS idx_companies_parent_company_id ON organization.companies (parent_company_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_companies_metadata_gin ON organization.companies USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_companies_metadata_deleted_at ON organization.companies ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_companies_metadata_created_at ON organization.companies ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_companies_metadata_updated_at ON organization.companies ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION organization.companies_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS companies_insert_audit ON organization.companies;
CREATE TRIGGER companies_insert_audit BEFORE INSERT ON organization.companies
    FOR EACH ROW EXECUTE FUNCTION organization.companies_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS companies_update_audit ON organization.companies;
CREATE TRIGGER companies_update_audit BEFORE UPDATE ON organization.companies
    FOR EACH ROW EXECUTE FUNCTION organization.companies_audit_timestamp();
