-- Enum types for organization module
-- Generated by metaphor-schema

-- Create branch_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'branch_type') THEN
        CREATE TYPE branch_type AS ENUM ('head_office', 'branch', 'warehouse', 'outlet', 'factory');
    END IF;
END
$$;

-- Create org_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'org_status') THEN
        CREATE TYPE org_status AS ENUM ('active', 'inactive');
    END IF;
END
$$;

-- Create company_entity_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'company_entity_type') THEN
        CREATE TYPE company_entity_type AS ENUM ('pt', 'cv', 'firma', 'perorangan', 'koperasi', 'yayasan', 'bumn', 'other');
    END IF;
END
$$;

-- Create company_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'company_status') THEN
        CREATE TYPE company_status AS ENUM ('active', 'inactive', 'suspended', 'dissolved');
    END IF;
END
$$;

