-- Migration: Create levels table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS organization;

CREATE TABLE IF NOT EXISTS organization.levels (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    grade TEXT,
    order_number INTEGER,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_levels_company_id_name ON organization.levels (company_id, name) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_levels_company_id_order_number ON organization.levels (company_id, order_number);

CREATE INDEX IF NOT EXISTS idx_levels_company_id ON organization.levels (company_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_levels_metadata_gin ON organization.levels USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_levels_metadata_deleted_at ON organization.levels ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_levels_metadata_created_at ON organization.levels ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_levels_metadata_updated_at ON organization.levels ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION organization.levels_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS levels_insert_audit ON organization.levels;
CREATE TRIGGER levels_insert_audit BEFORE INSERT ON organization.levels
    FOR EACH ROW EXECUTE FUNCTION organization.levels_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS levels_update_audit ON organization.levels;
CREATE TRIGGER levels_update_audit BEFORE UPDATE ON organization.levels
    FOR EACH ROW EXECUTE FUNCTION organization.levels_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE organization.levels ADD CONSTRAINT fk_levels_company_id FOREIGN KEY (company_id) REFERENCES organization.companies (id);
