-- Migration: Create org_units table
-- Generated by metaphor-schema

-- Create org_unit_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'org_unit_kind') THEN
        CREATE TYPE org_unit_kind AS ENUM ('root', 'company', 'branch');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS organization;

CREATE TABLE IF NOT EXISTS organization.org_units (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    kind org_unit_kind NOT NULL,
    parent_id UUID,
    code TEXT,
    name TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_org_units_kind ON organization.org_units (kind) WHERE kind = 'root';

CREATE INDEX IF NOT EXISTS idx_org_units_parent_id ON organization.org_units (parent_id);

CREATE INDEX IF NOT EXISTS idx_org_units_kind ON organization.org_units (kind);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_org_units_metadata_gin ON organization.org_units USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_org_units_metadata_deleted_at ON organization.org_units ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_org_units_metadata_created_at ON organization.org_units ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_org_units_metadata_updated_at ON organization.org_units ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION organization.org_units_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS org_units_insert_audit ON organization.org_units;
CREATE TRIGGER org_units_insert_audit BEFORE INSERT ON organization.org_units
    FOR EACH ROW EXECUTE FUNCTION organization.org_units_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS org_units_update_audit ON organization.org_units;
CREATE TRIGGER org_units_update_audit BEFORE UPDATE ON organization.org_units
    FOR EACH ROW EXECUTE FUNCTION organization.org_units_audit_timestamp();
