//! Event handler trait for Branch events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::BranchEvent;

/// Event handler for Branch events.
/// Implement this trait to react to Branch lifecycle events.
pub trait BranchEventHandler: EventHandler<BranchEvent> {}
