//! Domain events for Branch entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Branch;

/// Domain events for Branch — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Branch>)` variant.
pub type BranchEvent = CrudEvent<Branch>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Branch events.
pub type BranchEventPublisher = Arc<dyn CrudEventPublisher<Branch> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBranchEventPublisher = NoOpCrudEventPublisher<Branch>;
