//! Event handler trait for CompanyIndustry events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CompanyIndustryEvent;

/// Event handler for CompanyIndustry events.
/// Implement this trait to react to CompanyIndustry lifecycle events.
pub trait CompanyIndustryEventHandler: EventHandler<CompanyIndustryEvent> {}
