//! Domain events for Company entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Company;

/// Domain events for Company — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Company>)` variant.
pub type CompanyEvent = CrudEvent<Company>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Company events.
pub type CompanyEventPublisher = Arc<dyn CrudEventPublisher<Company> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCompanyEventPublisher = NoOpCrudEventPublisher<Company>;
