//! Domain events for CompanyIndustry entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::CompanyIndustry;

/// Domain events for CompanyIndustry — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<CompanyIndustry>)` variant.
pub type CompanyIndustryEvent = CrudEvent<CompanyIndustry>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for CompanyIndustry events.
pub type CompanyIndustryEventPublisher = Arc<dyn CrudEventPublisher<CompanyIndustry> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCompanyIndustryEventPublisher = NoOpCrudEventPublisher<CompanyIndustry>;
