//! Domain events for Department entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Department;

/// Domain events for Department — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Department>)` variant.
pub type DepartmentEvent = CrudEvent<Department>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Department events.
pub type DepartmentEventPublisher = Arc<dyn CrudEventPublisher<Department> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopDepartmentEventPublisher = NoOpCrudEventPublisher<Department>;
