//! Event handler trait for Department events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::DepartmentEvent;

/// Event handler for Department events.
/// Implement this trait to react to Department lifecycle events.
pub trait DepartmentEventHandler: EventHandler<DepartmentEvent> {}
