//! Domain events for Industry entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Industry;

/// Domain events for Industry — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Industry>)` variant.
pub type IndustryEvent = CrudEvent<Industry>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Industry events.
pub type IndustryEventPublisher = Arc<dyn CrudEventPublisher<Industry> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopIndustryEventPublisher = NoOpCrudEventPublisher<Industry>;
