//! Domain events for Level entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Level;

/// Domain events for Level — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Level>)` variant.
pub type LevelEvent = CrudEvent<Level>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Level events.
pub type LevelEventPublisher = Arc<dyn CrudEventPublisher<Level> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopLevelEventPublisher = NoOpCrudEventPublisher<Level>;
