//! Event handler trait for Level events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::LevelEvent;

/// Event handler for Level events.
/// Implement this trait to react to Level lifecycle events.
pub trait LevelEventHandler: EventHandler<LevelEvent> {}
