//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod branch_events;
pub mod branch_event_handlers;
pub mod company_events;
pub mod company_event_handlers;
pub mod department_events;
pub mod department_event_handlers;

pub use branch_events::{BranchEvent, BranchEventPublisher, NoopBranchEventPublisher};
pub use branch_event_handlers::BranchEventHandler;
pub use company_events::{CompanyEvent, CompanyEventPublisher, NoopCompanyEventPublisher};
pub use company_event_handlers::CompanyEventHandler;
pub use department_events::{DepartmentEvent, DepartmentEventPublisher, NoopDepartmentEventPublisher};
pub use department_event_handlers::DepartmentEventHandler;

// <<< CUSTOM
// END CUSTOM
