//! Event handler trait for OrgUnit events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::OrgUnitEvent;

/// Event handler for OrgUnit events.
/// Implement this trait to react to OrgUnit lifecycle events.
pub trait OrgUnitEventHandler: EventHandler<OrgUnitEvent> {}
