//! Domain events for OrgUnit entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::OrgUnit;

/// Domain events for OrgUnit — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<OrgUnit>)` variant.
pub type OrgUnitEvent = CrudEvent<OrgUnit>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for OrgUnit events.
pub type OrgUnitEventPublisher = Arc<dyn CrudEventPublisher<OrgUnit> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopOrgUnitEventPublisher = NoOpCrudEventPublisher<OrgUnit>;
