//! Domain events for Position entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Position;

/// Domain events for Position — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Position>)` variant.
pub type PositionEvent = CrudEvent<Position>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Position events.
pub type PositionEventPublisher = Arc<dyn CrudEventPublisher<Position> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPositionEventPublisher = NoOpCrudEventPublisher<Position>;
