//! Event handler trait for Position events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PositionEvent;

/// Event handler for Position events.
/// Implement this trait to react to Position lifecycle events.
pub trait PositionEventHandler: EventHandler<PositionEvent> {}
