//! Event handler trait for Structure events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::StructureEvent;

/// Event handler for Structure events.
/// Implement this trait to react to Structure lifecycle events.
pub trait StructureEventHandler: EventHandler<StructureEvent> {}
