//! Domain events for Structure entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Structure;

/// Domain events for Structure — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Structure>)` variant.
pub type StructureEvent = CrudEvent<Structure>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Structure events.
pub type StructureEventPublisher = Arc<dyn CrudEventPublisher<Structure> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopStructureEventPublisher = NoOpCrudEventPublisher<Structure>;
