//! Event subscriber type aliases for Organization module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::BranchEvent;
use crate::domain::event::CompanyEvent;
use crate::domain::event::DepartmentEvent;

/// Subscriber for Branch events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type BranchEventSubscriber = GenericEventSubscriber<BranchEvent>;

/// Subscriber for Company events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type CompanyEventSubscriber = GenericEventSubscriber<CompanyEvent>;

/// Subscriber for Department events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type DepartmentEventSubscriber = GenericEventSubscriber<DepartmentEvent>;

// <<< CUSTOM
// END CUSTOM
