//! Organization Event Subscriptions
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Cross-module event subscriptions. Each entity subscriber is a type alias
//! over `GenericEventSubscriber` from backbone-messaging.

pub mod handlers;
pub mod registry;

pub use handlers::*;
pub use registry::SubscriptionRegistry;

pub use handlers::BranchEventSubscriber;
pub use handlers::CompanyEventSubscriber;
pub use handlers::CompanyIndustryEventSubscriber;
pub use handlers::DepartmentEventSubscriber;
pub use handlers::IndustryEventSubscriber;
