//! OrgUnit seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial OrgUnit data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ORGUNIT SEEDER
// ============================================================================

/// Seeder for org_unit
pub struct SeedOrgUnitSeeder;

impl SeedOrgUnitSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedOrgUnitSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedOrgUnitSeeder {
    fn name(&self) -> &'static str {
        "SeedOrgUnitSeeder"
    }

    fn order(&self) -> i32 {
        8
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if organization.org_units table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM organization.org_units")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/org_unit_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM organization.org_units")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
