//! Repository trait for Branch aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Branch aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Branch, BranchType, OrgStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BranchPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl BranchPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct BranchPaginatedResult {
    pub data: Vec<Branch>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BranchFilter {
    pub company_id: Option<Uuid>,
    pub code: Option<String>,
    pub name: Option<String>,
    pub branch_type: Option<BranchType>,
    pub is_head_office: Option<bool>,
    pub npwp: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub address: Option<String>,
    pub city: Option<String>,
    pub province: Option<String>,
    pub postal_code: Option<String>,
    pub country: Option<String>,
    pub status: Option<OrgStatus>,
}

impl BranchFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.code.is_some() || self.name.is_some() || self.branch_type.is_some() || self.is_head_office.is_some() || self.npwp.is_some() || self.email.is_some() || self.phone.is_some() || self.address.is_some() || self.city.is_some() || self.province.is_some() || self.postal_code.is_some() || self.country.is_some() || self.status.is_some()
    }
}

/// Repository trait for Branch aggregate
///
/// This trait defines the persistence contract for Branch entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait BranchRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new branch entity
    async fn save(&self, entity: &Branch) -> Result<Branch>;

    /// Find branch by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Branch>>;

    /// Find all branch entities
    async fn find_all(&self) -> Result<Vec<Branch>>;

    /// Update branch by ID
    async fn update(&self, id: &str, entity: &Branch) -> Result<Option<Branch>>;

    /// Delete branch by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List branch with pagination
    async fn list(&self, params: BranchPaginationParams) -> Result<BranchPaginatedResult>;

    /// List branch with pagination and filters
    async fn list_with_filters(&self, params: BranchPaginationParams, filters: BranchFilter) -> Result<BranchPaginatedResult>;

    /// Count all branch entities
    async fn count(&self) -> Result<u64>;

    /// Count branch entities matching filters
    async fn count_with_filters(&self, filters: BranchFilter) -> Result<u64>;

    /// Check if branch exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete branch by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted branch by ID
    async fn restore(&self, id: &str) -> Result<Option<Branch>>;

    /// List soft-deleted branch entities
    async fn list_deleted(&self, params: BranchPaginationParams) -> Result<BranchPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save branch entities
    async fn bulk_save(&self, entities: &[Branch]) -> Result<Vec<Branch>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
