//! Repository trait for Company aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Company aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Company, CompanyEntityType, CompanyStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CompanyPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CompanyPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CompanyPaginatedResult {
    pub data: Vec<Company>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CompanyFilter {
    pub code: Option<String>,
    pub legal_name: Option<String>,
    pub trade_name: Option<String>,
    pub npwp: Option<String>,
    pub nib: Option<String>,
    pub entity_type: Option<CompanyEntityType>,
    pub base_currency: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub address: Option<String>,
    pub city: Option<String>,
    pub province: Option<String>,
    pub postal_code: Option<String>,
    pub country: Option<String>,
    pub parent_company_id: Option<Uuid>,
    pub is_default: Option<bool>,
    pub status: Option<CompanyStatus>,
    pub notes: Option<String>,
}

impl CompanyFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.code.is_some() || self.legal_name.is_some() || self.trade_name.is_some() || self.npwp.is_some() || self.nib.is_some() || self.entity_type.is_some() || self.base_currency.is_some() || self.email.is_some() || self.phone.is_some() || self.address.is_some() || self.city.is_some() || self.province.is_some() || self.postal_code.is_some() || self.country.is_some() || self.parent_company_id.is_some() || self.is_default.is_some() || self.status.is_some() || self.notes.is_some()
    }
}

/// Repository trait for Company aggregate
///
/// This trait defines the persistence contract for Company entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CompanyRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new company entity
    async fn save(&self, entity: &Company) -> Result<Company>;

    /// Find company by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Company>>;

    /// Find all company entities
    async fn find_all(&self) -> Result<Vec<Company>>;

    /// Update company by ID
    async fn update(&self, id: &str, entity: &Company) -> Result<Option<Company>>;

    /// Delete company by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List company with pagination
    async fn list(&self, params: CompanyPaginationParams) -> Result<CompanyPaginatedResult>;

    /// List company with pagination and filters
    async fn list_with_filters(&self, params: CompanyPaginationParams, filters: CompanyFilter) -> Result<CompanyPaginatedResult>;

    /// Count all company entities
    async fn count(&self) -> Result<u64>;

    /// Count company entities matching filters
    async fn count_with_filters(&self, filters: CompanyFilter) -> Result<u64>;

    /// Check if company exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete company by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted company by ID
    async fn restore(&self, id: &str) -> Result<Option<Company>>;

    /// List soft-deleted company entities
    async fn list_deleted(&self, params: CompanyPaginationParams) -> Result<CompanyPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save company entities
    async fn bulk_save(&self, entities: &[Company]) -> Result<Vec<Company>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
