//! Repository trait for CompanyIndustry aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the CompanyIndustry aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::CompanyIndustry;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CompanyIndustryPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CompanyIndustryPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CompanyIndustryPaginatedResult {
    pub data: Vec<CompanyIndustry>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CompanyIndustryFilter {
    pub company_id: Option<Uuid>,
    pub industry_id: Option<Uuid>,
    pub is_primary: Option<bool>,
}

impl CompanyIndustryFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.industry_id.is_some() || self.is_primary.is_some()
    }
}

/// Repository trait for CompanyIndustry aggregate
///
/// This trait defines the persistence contract for CompanyIndustry entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CompanyIndustryRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new company_industry entity
    async fn save(&self, entity: &CompanyIndustry) -> Result<CompanyIndustry>;

    /// Find company_industry by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<CompanyIndustry>>;

    /// Find all company_industry entities
    async fn find_all(&self) -> Result<Vec<CompanyIndustry>>;

    /// Update company_industry by ID
    async fn update(&self, id: &str, entity: &CompanyIndustry) -> Result<Option<CompanyIndustry>>;

    /// Delete company_industry by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List company_industry with pagination
    async fn list(&self, params: CompanyIndustryPaginationParams) -> Result<CompanyIndustryPaginatedResult>;

    /// List company_industry with pagination and filters
    async fn list_with_filters(&self, params: CompanyIndustryPaginationParams, filters: CompanyIndustryFilter) -> Result<CompanyIndustryPaginatedResult>;

    /// Count all company_industry entities
    async fn count(&self) -> Result<u64>;

    /// Count company_industry entities matching filters
    async fn count_with_filters(&self, filters: CompanyIndustryFilter) -> Result<u64>;

    /// Check if company_industry exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete company_industry by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted company_industry by ID
    async fn restore(&self, id: &str) -> Result<Option<CompanyIndustry>>;

    /// List soft-deleted company_industry entities
    async fn list_deleted(&self, params: CompanyIndustryPaginationParams) -> Result<CompanyIndustryPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save company_industry entities
    async fn bulk_save(&self, entities: &[CompanyIndustry]) -> Result<Vec<CompanyIndustry>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
