//! Repository trait for Department aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Department aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Department, OrgStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DepartmentPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl DepartmentPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct DepartmentPaginatedResult {
    pub data: Vec<Department>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DepartmentFilter {
    pub company_id: Option<Uuid>,
    pub code: Option<String>,
    pub name: Option<String>,
    pub parent_id: Option<Uuid>,
    pub is_group: Option<bool>,
    pub branch_id: Option<Uuid>,
    pub manager_id: Option<Uuid>,
    pub status: Option<OrgStatus>,
}

impl DepartmentFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.code.is_some() || self.name.is_some() || self.parent_id.is_some() || self.is_group.is_some() || self.branch_id.is_some() || self.manager_id.is_some() || self.status.is_some()
    }
}

/// Repository trait for Department aggregate
///
/// This trait defines the persistence contract for Department entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait DepartmentRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new department entity
    async fn save(&self, entity: &Department) -> Result<Department>;

    /// Find department by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Department>>;

    /// Find all department entities
    async fn find_all(&self) -> Result<Vec<Department>>;

    /// Update department by ID
    async fn update(&self, id: &str, entity: &Department) -> Result<Option<Department>>;

    /// Delete department by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List department with pagination
    async fn list(&self, params: DepartmentPaginationParams) -> Result<DepartmentPaginatedResult>;

    /// List department with pagination and filters
    async fn list_with_filters(&self, params: DepartmentPaginationParams, filters: DepartmentFilter) -> Result<DepartmentPaginatedResult>;

    /// Count all department entities
    async fn count(&self) -> Result<u64>;

    /// Count department entities matching filters
    async fn count_with_filters(&self, filters: DepartmentFilter) -> Result<u64>;

    /// Check if department exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete department by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted department by ID
    async fn restore(&self, id: &str) -> Result<Option<Department>>;

    /// List soft-deleted department entities
    async fn list_deleted(&self, params: DepartmentPaginationParams) -> Result<DepartmentPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save department entities
    async fn bulk_save(&self, entities: &[Department]) -> Result<Vec<Department>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
