//! Repository trait for Industry aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Industry aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Industry, KBLISector, OrgStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct IndustryPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl IndustryPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct IndustryPaginatedResult {
    pub data: Vec<Industry>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct IndustryFilter {
    pub code: Option<String>,
    pub name: Option<String>,
    pub sector: Option<KBLISector>,
    pub parent_id: Option<Uuid>,
    pub status: Option<OrgStatus>,
}

impl IndustryFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.code.is_some() || self.name.is_some() || self.sector.is_some() || self.parent_id.is_some() || self.status.is_some()
    }
}

/// Repository trait for Industry aggregate
///
/// This trait defines the persistence contract for Industry entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait IndustryRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new industry entity
    async fn save(&self, entity: &Industry) -> Result<Industry>;

    /// Find industry by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Industry>>;

    /// Find all industry entities
    async fn find_all(&self) -> Result<Vec<Industry>>;

    /// Update industry by ID
    async fn update(&self, id: &str, entity: &Industry) -> Result<Option<Industry>>;

    /// Delete industry by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List industry with pagination
    async fn list(&self, params: IndustryPaginationParams) -> Result<IndustryPaginatedResult>;

    /// List industry with pagination and filters
    async fn list_with_filters(&self, params: IndustryPaginationParams, filters: IndustryFilter) -> Result<IndustryPaginatedResult>;

    /// Count all industry entities
    async fn count(&self) -> Result<u64>;

    /// Count industry entities matching filters
    async fn count_with_filters(&self, filters: IndustryFilter) -> Result<u64>;

    /// Check if industry exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete industry by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted industry by ID
    async fn restore(&self, id: &str) -> Result<Option<Industry>>;

    /// List soft-deleted industry entities
    async fn list_deleted(&self, params: IndustryPaginationParams) -> Result<IndustryPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save industry entities
    async fn bulk_save(&self, entities: &[Industry]) -> Result<Vec<Industry>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
