//! Repository trait for Level aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Level aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::Level;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct LevelPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl LevelPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct LevelPaginatedResult {
    pub data: Vec<Level>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct LevelFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub grade: Option<String>,
}

impl LevelFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.grade.is_some()
    }
}

/// Repository trait for Level aggregate
///
/// This trait defines the persistence contract for Level entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait LevelRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new level entity
    async fn save(&self, entity: &Level) -> Result<Level>;

    /// Find level by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Level>>;

    /// Find all level entities
    async fn find_all(&self) -> Result<Vec<Level>>;

    /// Update level by ID
    async fn update(&self, id: &str, entity: &Level) -> Result<Option<Level>>;

    /// Delete level by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List level with pagination
    async fn list(&self, params: LevelPaginationParams) -> Result<LevelPaginatedResult>;

    /// List level with pagination and filters
    async fn list_with_filters(&self, params: LevelPaginationParams, filters: LevelFilter) -> Result<LevelPaginatedResult>;

    /// Count all level entities
    async fn count(&self) -> Result<u64>;

    /// Count level entities matching filters
    async fn count_with_filters(&self, filters: LevelFilter) -> Result<u64>;

    /// Check if level exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete level by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted level by ID
    async fn restore(&self, id: &str) -> Result<Option<Level>>;

    /// List soft-deleted level entities
    async fn list_deleted(&self, params: LevelPaginationParams) -> Result<LevelPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save level entities
    async fn bulk_save(&self, entities: &[Level]) -> Result<Vec<Level>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
