//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod branch_repository;
pub mod company_repository;
pub mod company_industry_repository;
pub mod department_repository;
pub mod industry_repository;
pub mod level_repository;
pub mod position_repository;
pub mod structure_repository;

// Re-exports
pub use branch_repository::{
    BranchRepository,
    BranchPaginationParams,
    BranchPaginatedResult,
    BranchFilter,
};
pub use company_repository::{
    CompanyRepository,
    CompanyPaginationParams,
    CompanyPaginatedResult,
    CompanyFilter,
};
pub use company_industry_repository::{
    CompanyIndustryRepository,
    CompanyIndustryPaginationParams,
    CompanyIndustryPaginatedResult,
    CompanyIndustryFilter,
};
pub use department_repository::{
    DepartmentRepository,
    DepartmentPaginationParams,
    DepartmentPaginatedResult,
    DepartmentFilter,
};
pub use industry_repository::{
    IndustryRepository,
    IndustryPaginationParams,
    IndustryPaginatedResult,
    IndustryFilter,
};
pub use level_repository::{
    LevelRepository,
    LevelPaginationParams,
    LevelPaginatedResult,
    LevelFilter,
};
pub use position_repository::{
    PositionRepository,
    PositionPaginationParams,
    PositionPaginatedResult,
    PositionFilter,
};
pub use structure_repository::{
    StructureRepository,
    StructurePaginationParams,
    StructurePaginatedResult,
    StructureFilter,
};
