//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod branch_repository;
pub mod company_repository;
pub mod department_repository;

// Re-exports
pub use branch_repository::{
    BranchRepository,
    BranchPaginationParams,
    BranchPaginatedResult,
    BranchFilter,
};
pub use company_repository::{
    CompanyRepository,
    CompanyPaginationParams,
    CompanyPaginatedResult,
    CompanyFilter,
};
pub use department_repository::{
    DepartmentRepository,
    DepartmentPaginationParams,
    DepartmentPaginatedResult,
    DepartmentFilter,
};
