//! Repository trait for OrgUnit aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the OrgUnit aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{OrgUnit, OrgUnitKind};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OrgUnitPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl OrgUnitPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct OrgUnitPaginatedResult {
    pub data: Vec<OrgUnit>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OrgUnitFilter {
    pub kind: Option<OrgUnitKind>,
    pub parent_id: Option<Uuid>,
    pub code: Option<String>,
    pub name: Option<String>,
}

impl OrgUnitFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.kind.is_some() || self.parent_id.is_some() || self.code.is_some() || self.name.is_some()
    }
}

/// Repository trait for OrgUnit aggregate
///
/// This trait defines the persistence contract for OrgUnit entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait OrgUnitRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new org_unit entity
    async fn save(&self, entity: &OrgUnit) -> Result<OrgUnit>;

    /// Find org_unit by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<OrgUnit>>;

    /// Find all org_unit entities
    async fn find_all(&self) -> Result<Vec<OrgUnit>>;

    /// Update org_unit by ID
    async fn update(&self, id: &str, entity: &OrgUnit) -> Result<Option<OrgUnit>>;

    /// Delete org_unit by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List org_unit with pagination
    async fn list(&self, params: OrgUnitPaginationParams) -> Result<OrgUnitPaginatedResult>;

    /// List org_unit with pagination and filters
    async fn list_with_filters(&self, params: OrgUnitPaginationParams, filters: OrgUnitFilter) -> Result<OrgUnitPaginatedResult>;

    /// Count all org_unit entities
    async fn count(&self) -> Result<u64>;

    /// Count org_unit entities matching filters
    async fn count_with_filters(&self, filters: OrgUnitFilter) -> Result<u64>;

    /// Check if org_unit exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete org_unit by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted org_unit by ID
    async fn restore(&self, id: &str) -> Result<Option<OrgUnit>>;

    /// List soft-deleted org_unit entities
    async fn list_deleted(&self, params: OrgUnitPaginationParams) -> Result<OrgUnitPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save org_unit entities
    async fn bulk_save(&self, entities: &[OrgUnit]) -> Result<Vec<OrgUnit>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
