//! Repository trait for Position aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Position aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::Position;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PositionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PositionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PositionPaginatedResult {
    pub data: Vec<Position>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PositionFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub code: Option<String>,
    pub description: Option<String>,
}

impl PositionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.code.is_some() || self.description.is_some()
    }
}

/// Repository trait for Position aggregate
///
/// This trait defines the persistence contract for Position entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PositionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new position entity
    async fn save(&self, entity: &Position) -> Result<Position>;

    /// Find position by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Position>>;

    /// Find all position entities
    async fn find_all(&self) -> Result<Vec<Position>>;

    /// Update position by ID
    async fn update(&self, id: &str, entity: &Position) -> Result<Option<Position>>;

    /// Delete position by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List position with pagination
    async fn list(&self, params: PositionPaginationParams) -> Result<PositionPaginatedResult>;

    /// List position with pagination and filters
    async fn list_with_filters(&self, params: PositionPaginationParams, filters: PositionFilter) -> Result<PositionPaginatedResult>;

    /// Count all position entities
    async fn count(&self) -> Result<u64>;

    /// Count position entities matching filters
    async fn count_with_filters(&self, filters: PositionFilter) -> Result<u64>;

    /// Check if position exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete position by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted position by ID
    async fn restore(&self, id: &str) -> Result<Option<Position>>;

    /// List soft-deleted position entities
    async fn list_deleted(&self, params: PositionPaginationParams) -> Result<PositionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save position entities
    async fn bulk_save(&self, entities: &[Position]) -> Result<Vec<Position>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
