//! Repository trait for Structure aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Structure aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::Structure;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct StructurePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl StructurePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct StructurePaginatedResult {
    pub data: Vec<Structure>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct StructureFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub parent_id: Option<Uuid>,
    pub manager_id: Option<Uuid>,
}

impl StructureFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.parent_id.is_some() || self.manager_id.is_some()
    }
}

/// Repository trait for Structure aggregate
///
/// This trait defines the persistence contract for Structure entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait StructureRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new structure entity
    async fn save(&self, entity: &Structure) -> Result<Structure>;

    /// Find structure by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Structure>>;

    /// Find all structure entities
    async fn find_all(&self) -> Result<Vec<Structure>>;

    /// Update structure by ID
    async fn update(&self, id: &str, entity: &Structure) -> Result<Option<Structure>>;

    /// Delete structure by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List structure with pagination
    async fn list(&self, params: StructurePaginationParams) -> Result<StructurePaginatedResult>;

    /// List structure with pagination and filters
    async fn list_with_filters(&self, params: StructurePaginationParams, filters: StructureFilter) -> Result<StructurePaginatedResult>;

    /// Count all structure entities
    async fn count(&self) -> Result<u64>;

    /// Count structure entities matching filters
    async fn count_with_filters(&self, filters: StructureFilter) -> Result<u64>;

    /// Check if structure exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete structure by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted structure by ID
    async fn restore(&self, id: &str) -> Result<Option<Structure>>;

    /// List soft-deleted structure entities
    async fn list_deleted(&self, params: StructurePaginationParams) -> Result<StructurePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save structure entities
    async fn bulk_save(&self, entities: &[Structure]) -> Result<Vec<Structure>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
