//! Repository for Branch entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Branch SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Branch, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Branch;

/// Table name for Branch entities
pub const TABLE_NAME: &str = "organization.branches";

/// Repository for Branch entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct BranchRepository(
    backbone_orm::GenericCrudRepository<Branch, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for BranchRepository {
    type Target = backbone_orm::GenericCrudRepository<Branch, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl BranchRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated branch creation writes.
///
/// Mirrors the raw column shape rather than the `Branch` entity: `branch_type` binds as `&str` and is
/// cast at the DB (`$5::branch_type`), so a bad value fails as a DB error rather than a deserialize
/// panic. The NPWP is expected already validated by the caller.
pub struct NewBranchRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub code: &'a str,
    pub name: &'a str,
    pub branch_type: &'a str,
    pub is_head_office: bool,
    pub npwp: Option<&'a String>,
    pub email: Option<&'a String>,
    pub phone: Option<&'a String>,
    pub address: Option<&'a String>,
}

/// Hand-written Branch SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate, repositories hold the SQL.
impl BranchRepository {
    /// Create a branch.
    ///
    /// RLS scope (ADR-0008), DTO-company pattern: the company is on the DTO — the caller wraps this in
    /// `with_company_scope(Some(company_id))` because the INSERT's WITH CHECK needs `app.company_id`
    /// bound or it is rejected under the app role.
    pub async fn insert_branch(
        &self,
        pool: &PgPool,
        b: &NewBranchRow<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO organization.branches
                    (id, company_id, code, name, branch_type, is_head_office, npwp, email, phone, address, status)
                   VALUES ($1,$2,$3,$4,$5::branch_type,$6,$7,$8,$9,$10,'active'::org_status)"#,
            )
            .bind(b.id)
            .bind(b.company_id)
            .bind(b.code)
            .bind(b.name)
            .bind(b.branch_type)
            .bind(b.is_head_office)
            .bind(b.npwp)
            .bind(b.email)
            .bind(b.phone)
            .bind(b.address),
        )
        .await?;
        Ok(())
    }

    /// The company a branch belongs to — the link probe behind the same-company invariant. `Ok(None)`
    /// = no such live branch.
    ///
    /// RLS scope (ADR-0008), param-company pattern: the caller wraps this in
    /// `with_company_scope(Some(company_id))` to fence the probe, and keeps its explicit
    /// `c != company_id` check as defense-in-depth on top of that fence.
    pub async fn find_owner_company(
        &self,
        pool: &PgPool,
        branch_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                "SELECT company_id FROM organization.branches WHERE id=$1 AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(branch_id),
        )
        .await
    }
}

backbone_core::impl_crud_repository!(BranchRepository, Branch, soft_delete);
