//! Repository for Branch entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Branch SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Branch, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.
//!
//! RLS LAW (ADR-0029): the module is tenant-agnostic and ships no row fence. Branch rows carry no
//! company column — a branch's place in the org tree is its `org_units` node (id = branch id,
//! kind = 'branch'), minted in the same transaction as the branch row. Isolation is installed by
//! the COMPOSING service's tenancy decorator.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

// The typed multi-row read twin lives only in the legacy `company_scope` module. Its
// connection discipline is what this repository needs — request-dedicated connection when the
// composing service bound one, plain pool otherwise. The helper's legacy task-local branch is
// never taken: this module sets no legacy scope of its own (ADR-0029).
use backbone_orm::company_scope::fetch_all_scoped;

use crate::domain::entity::Branch;

/// Table name for Branch entities
pub const TABLE_NAME: &str = "organization.branches";

/// Repository for Branch entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct BranchRepository(
    backbone_orm::GenericCrudRepository<Branch, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for BranchRepository {
    type Target = backbone_orm::GenericCrudRepository<Branch, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl BranchRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated branch creation writes.
///
/// Mirrors the raw column shape rather than the `Branch` entity: `branch_type` binds as `&str` and is
/// cast at the DB (`$4::branch_type`), so a bad value fails as a DB error rather than a deserialize
/// panic. The NPWP is expected already validated by the caller. `parent_unit` is the org-units node
/// the branch attaches under (a company or an ancestor branch) — it names the NODE row, not a
/// column on branches.
pub struct NewBranchRow<'a> {
    pub id: Uuid,
    pub parent_unit: Uuid,
    pub code: &'a str,
    pub name: &'a str,
    pub branch_type: &'a str,
    pub is_head_office: bool,
    pub npwp: Option<&'a String>,
    pub email: Option<&'a String>,
    pub phone: Option<&'a String>,
    pub address: Option<&'a String>,
}

/// Hand-written Branch SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate, repositories hold the SQL.
impl BranchRepository {
    /// Create a branch on the CALLER'S transaction — the branch row and its org-units node commit
    /// (or roll back) as one unit with the caller's unit of work.
    pub async fn insert_branch_on(
        &self,
        conn: &mut sqlx::PgConnection,
        b: &NewBranchRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO organization.branches
                (id, code, name, branch_type, is_head_office, npwp, email, phone, address, status)
               VALUES ($1,$2,$3,$4::branch_type,$5,$6,$7,$8,$9,'active'::org_status)"#,
        )
        .bind(b.id)
        .bind(b.code)
        .bind(b.name)
        .bind(b.branch_type)
        .bind(b.is_head_office)
        .bind(b.npwp)
        .bind(b.email)
        .bind(b.phone)
        .bind(b.address)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Mint the branch's org-units node on the CALLER'S transaction — kind 'branch', parent the
    /// caller-validated `parent_unit` (a company node or an ancestor branch node). The node id IS
    /// the branch id (ADR-0028 spine contract: ids are stable, references in consuming modules
    /// already point at valid nodes).
    pub async fn insert_branch_node_on(
        &self,
        conn: &mut sqlx::PgConnection,
        branch_id: Uuid,
        parent_unit: Uuid,
        code: &str,
        name: &str,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO organization.org_units (id, kind, parent_id, code, name)
               VALUES ($1, 'branch', $2, $3, $4)"#,
        )
        .bind(branch_id)
        .bind(parent_unit)
        .bind(code)
        .bind(name)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Whether a live (non-soft-deleted) branch exists — the department link probe. A branch id
    /// outside the caller's visible scope is simply absent (the composing service's decorator
    /// fences the read, ADR-0029).
    pub async fn exists_live(
        &self,
        pool: &PgPool,
        branch_id: Uuid,
    ) -> Result<bool, sqlx::Error> {
        let row = backbone_orm::org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                "SELECT id FROM organization.branches WHERE id=$1 AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(branch_id),
        )
        .await?;
        Ok(row.is_some())
    }
}

/// The exact row the onboarding path writes for a new company's head-office branch.
///
/// A deliberately narrower column set than [`NewBranchRow`]: onboarding only knows the code and
/// name, and the statement must stay verbatim rather than bind NULLs into columns it never named.
/// The org-units node (under the freshly minted company node) is minted by
/// [`Self::insert_branch_node_on`] in the same transaction.
pub struct NewHeadOfficeBranchRow<'a> {
    pub id: Uuid,
    pub code: &'a str,
    pub name: &'a str,
}

/// Hand-written Branch SQL for the onboarding unit of work.
impl BranchRepository {
    /// Create the head-office branch for a company being onboarded, on the CALLER'S transaction —
    /// it must commit as one unit with the company INSERT and both org-units nodes that precede
    /// and follow it.
    pub async fn insert_head_office_on(
        &self,
        conn: &mut sqlx::PgConnection,
        b: &NewHeadOfficeBranchRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO organization.branches
                (id, code, name, branch_type, is_head_office, status)
               VALUES ($1,$2,$3,'head_office'::branch_type,TRUE,'active'::org_status)"#,
        )
        .bind(b.id)
        .bind(b.code)
        .bind(b.name)
        .execute(conn)
        .await?;
        Ok(())
    }
}

/// Lightweight read shape for the branch level of the hierarchy endpoint.
/// `branch_type`/`status` cast to `::text` so this binds as `String`.
#[derive(Debug, sqlx::FromRow)]
pub struct BranchHierarchyRow {
    pub id: Uuid,
    pub code: String,
    pub name: String,
    pub branch_type: String,
    pub is_head_office: bool,
    pub city: Option<String>,
    pub status: String,
}

/// Hand-written Branch SQL for the hierarchy read.
impl BranchRepository {
    /// All live (non-soft-deleted) branches under one company's org-units SUBTREE (the company
    /// node, its branches, and chained head-office descendants — the same membership the old
    /// company column expressed), head office first.
    pub async fn list_live_by_unit(
        &self,
        pool: &PgPool,
        company_unit: Uuid,
    ) -> Result<Vec<BranchHierarchyRow>, sqlx::Error> {
        fetch_all_scoped(
            pool,
            sqlx::query_as::<_, BranchHierarchyRow>(
                r#"SELECT b.id, b.code, b.name, b.branch_type::text, b.is_head_office, b.city, b.status::text
                   FROM organization.branches b
                   WHERE b.id IN (SELECT organization.org_unit_subtree(ARRAY[$1]))
                     AND (b.metadata->>'deleted_at') IS NULL
                   ORDER BY b.is_head_office DESC, b.code"#,
            )
            .bind(company_unit),
        )
        .await
    }
}

backbone_core::impl_crud_repository!(BranchRepository, Branch, soft_delete);
