//! Repository for Branch entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Branch, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Branch;

/// Table name for Branch entities
pub const TABLE_NAME: &str = "organization.branches";

/// Repository for Branch entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct BranchRepository(
    backbone_orm::GenericCrudRepository<Branch, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for BranchRepository {
    type Target = backbone_orm::GenericCrudRepository<Branch, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl BranchRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(BranchRepository, Branch, soft_delete);
