//! Repository for Company entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Company SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Company, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Company;

/// Table name for Company entities
pub const TABLE_NAME: &str = "organization.companies";

/// Repository for Company entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CompanyRepository(
    backbone_orm::GenericCrudRepository<Company, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CompanyRepository {
    type Target = backbone_orm::GenericCrudRepository<Company, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CompanyRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// Hand-written Company SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate, repositories hold the SQL.
impl CompanyRepository {
    /// Probe whether a live (non-soft-deleted) company exists.
    ///
    /// The caller wraps this in `with_company_scope(Some(id))` — the id being probed IS the company, so
    /// the probe is fenced to it (ADR-0008).
    pub async fn find_live_id(&self, pool: &PgPool, id: Uuid) -> Result<Option<Uuid>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                "SELECT id FROM organization.companies WHERE id=$1 AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(id),
        )
        .await
    }
}

backbone_core::impl_crud_repository!(CompanyRepository, Company, soft_delete);
