//! Repository for Company entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Company SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Company, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.
//!
//! RLS LAW (ADR-0029): companies is the registry of legal entities and carries NO tenant axis —
//! it is intentionally unfenced under any declaration (see schema/models/index.model.yaml). Every
//! read here is a plain pool read on purpose. The org-units node helpers at the bottom are the
//! tree side of the same design: a company's place in the group tree is its org_units node
//! (id = company id, kind 'company'), minted in the same transaction as the company row.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::Company;

/// Table name for Company entities
pub const TABLE_NAME: &str = "organization.companies";

/// Repository for Company entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CompanyRepository(
    backbone_orm::GenericCrudRepository<Company, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CompanyRepository {
    type Target = backbone_orm::GenericCrudRepository<Company, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CompanyRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// Hand-written Company SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate, repositories hold the SQL.
impl CompanyRepository {
    /// Probe whether a live (non-soft-deleted) company exists.
    ///
    /// A PLAIN read: companies carries no tenant axis and is never fenced — the registry is
    /// visible to any authenticated caller; scoping lives in the org tree, not here (ADR-0029).
    pub async fn find_live_id(&self, pool: &PgPool, id: Uuid) -> Result<Option<Uuid>, sqlx::Error> {
        sqlx::query_scalar(
            "SELECT id FROM organization.companies WHERE id=$1 AND (metadata->>'deleted_at') IS NULL",
        )
        .bind(id)
        .fetch_optional(pool)
        .await
    }
}

/// The exact row the onboarding path writes for a new company.
///
/// Mirrors the raw column shape rather than the `Company` entity: `entity_type` binds as `&str` and
/// is cast at the DB (`$7::company_entity_type`). The NPWP is expected already validated by the
/// caller.
pub struct NewCompanyRow<'a> {
    pub id: Uuid,
    pub code: &'a str,
    pub legal_name: &'a str,
    pub trade_name: Option<&'a String>,
    pub npwp: Option<&'a String>,
    pub nib: Option<&'a String>,
    pub entity_type: &'a str,
    pub base_currency: &'a str,
    pub email: Option<&'a String>,
    pub phone: Option<&'a String>,
}

/// Hand-written Company SQL for the onboarding unit of work.
impl CompanyRepository {
    /// Probe whether a live company already holds `code`. `Ok(None)` = the code is free.
    ///
    /// A PLAIN read, on purpose: company-code uniqueness is a cross-company question asked
    /// before the company exists, and the registry is unfenced (ADR-0029). Binding any scope
    /// here would hide a conflicting company and let the probe wrongly report the code free.
    /// The partial unique index is the real arbiter; this is only a fast pre-check.
    pub async fn find_live_id_by_code(
        &self,
        pool: &PgPool,
        code: &str,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        sqlx::query_scalar(
            "SELECT id FROM organization.companies WHERE code=$1 AND (metadata->>'deleted_at') IS NULL",
        )
        .bind(code)
        .fetch_optional(pool)
        .await
    }

    /// Create a company.
    ///
    /// Takes the CALLER'S connection so the company, its org-units node, and its head-office
    /// branch commit as one unit. Not scoped: the company being written IS a registry row with
    /// no tenant axis (ADR-0029).
    ///
    /// **Leaks `sqlx::Error` deliberately** — the caller discriminates on `is_unique_violation()`
    /// and on the violated constraint's name to tell a duplicate code from a duplicate NPWP.
    pub async fn insert_company_on(
        &self,
        conn: &mut sqlx::PgConnection,
        c: &NewCompanyRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO organization.companies
                (id, code, legal_name, trade_name, npwp, nib, entity_type, base_currency, email, phone, status)
               VALUES ($1,$2,$3,$4,$5,$6,$7::company_entity_type,$8,$9,$10,'active'::company_status)"#,
        )
        .bind(c.id)
        .bind(c.code)
        .bind(c.legal_name)
        .bind(c.trade_name)
        .bind(c.npwp)
        .bind(c.nib)
        .bind(c.entity_type)
        .bind(c.base_currency)
        .bind(c.email)
        .bind(c.phone)
        .execute(conn)
        .await?;
        Ok(())
    }
}

/// Lightweight read shape for the company hierarchy endpoint. Enums are cast
/// to `::text` in the SELECT so this binds as plain `String` (no Rust enum
/// types needed here).
#[derive(Debug, sqlx::FromRow)]
pub struct CompanyHierarchyRow {
    pub id: Uuid,
    pub code: String,
    pub legal_name: String,
    pub trade_name: Option<String>,
    pub entity_type: String,
    pub base_currency: String,
    pub status: String,
}

/// Hand-written Company SQL for the hierarchy read.
impl CompanyRepository {
    /// Fetch a live (non-soft-deleted) company by id in the hierarchy read
    /// shape. `Ok(None)` = no such company (the hierarchy endpoint 404s).
    ///
    /// A PLAIN read: the registry is unfenced by design — any caller that can name a company
    /// may read its registry row; the scoped limbs of the hierarchy (branches, departments)
    /// are the fenced reads (ADR-0029).
    pub async fn find_live_by_id(
        &self,
        pool: &PgPool,
        id: Uuid,
    ) -> Result<Option<CompanyHierarchyRow>, sqlx::Error> {
        sqlx::query_as::<_, CompanyHierarchyRow>(
            "SELECT id, code, legal_name, trade_name, entity_type::text, base_currency, status::text \
             FROM organization.companies \
             WHERE id=$1 AND (metadata->>'deleted_at') IS NULL",
        )
        .bind(id)
        .fetch_optional(pool)
        .await
    }
}

/// Hand-written org-units tree SQL. The tree is what places companies and branches; these
/// helpers serve the write paths (branch creation validates the parent node; onboarding mints
/// the root/company nodes). They live in this user-owned repository because the org-unit
/// repository itself is generated. org_units is intentionally unfenced (ADR-0028: the tree is
/// what scopes everything else), so every read here is a plain pool read.
impl CompanyRepository {
    /// The kind of an org-units node, as text. `Ok(None)` = no such node. Used by branch
    /// creation to reject a parent that is not a company or branch node (the two kinds a
    /// branch may attach under — departments are masters, not nodes).
    pub async fn find_node_kind(
        &self,
        pool: &PgPool,
        unit_id: Uuid,
    ) -> Result<Option<String>, sqlx::Error> {
        sqlx::query_scalar("SELECT kind::text FROM organization.org_units WHERE id=$1")
            .bind(unit_id)
            .fetch_optional(pool)
            .await
    }

    /// The tenant root node (exactly one, guarded by a partial unique index).
    /// `Ok(None)` = the tree is empty (a fresh database before the spine migration's
    /// root insert, or a test that truncated the tree).
    pub async fn find_root_unit(&self, pool: &PgPool) -> Result<Option<Uuid>, sqlx::Error> {
        sqlx::query_scalar(
            "SELECT id FROM organization.org_units WHERE kind='root' AND parent_id IS NULL LIMIT 1",
        )
        .fetch_optional(pool)
        .await
    }

    /// Mint an org-units node on the CALLER'S transaction — the generic twin used by
    /// onboarding for the root node (if absent) and each new company's node. The branch
    /// twin (kind fixed 'branch') lives in [`BranchRepository::insert_branch_node_on`].
    /// `kind` binds as `&str` and is cast at the DB (`$3::org_unit_kind`).
    pub async fn insert_unit_node_on(
        &self,
        conn: &mut sqlx::PgConnection,
        id: Uuid,
        kind: &str,
        parent_id: Option<Uuid>,
        code: &str,
        name: &str,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO organization.org_units (id, kind, parent_id, code, name)
               VALUES ($1, $2::org_unit_kind, $3, $4, $5)"#,
        )
        .bind(id)
        .bind(kind)
        .bind(parent_id)
        .bind(code)
        .bind(name)
        .execute(conn)
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(CompanyRepository, Company, soft_delete);
