//! Repository for CompanyIndustry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<CompanyIndustry, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::CompanyIndustry;

/// Table name for CompanyIndustry entities
pub const TABLE_NAME: &str = "organization.company_industries";

/// Repository for CompanyIndustry entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CompanyIndustryRepository(
    backbone_orm::GenericCrudRepository<CompanyIndustry, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CompanyIndustryRepository {
    type Target = backbone_orm::GenericCrudRepository<CompanyIndustry, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CompanyIndustryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(CompanyIndustryRepository, CompanyIndustry, soft_delete);
