//! Repository for Company entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Company, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Company;

/// Table name for Company entities
pub const TABLE_NAME: &str = "organization.companies";

/// Repository for Company entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CompanyRepository(
    backbone_orm::GenericCrudRepository<Company, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CompanyRepository {
    type Target = backbone_orm::GenericCrudRepository<Company, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CompanyRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(CompanyRepository, Company, soft_delete);
