//! Repository for Department entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Department SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Department, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Department;

/// Table name for Department entities
pub const TABLE_NAME: &str = "organization.departments";

/// Repository for Department entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct DepartmentRepository(
    backbone_orm::GenericCrudRepository<Department, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for DepartmentRepository {
    type Target = backbone_orm::GenericCrudRepository<Department, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl DepartmentRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated department creation writes.
///
/// Mirrors the raw column shape rather than the `Department` entity. `parent_id`/`branch_id` are
/// expected already link-validated (exist AND same company) by the caller.
pub struct NewDepartmentRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub code: &'a str,
    pub name: &'a str,
    pub parent_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
    pub is_group: bool,
    pub manager_id: Option<Uuid>,
}

/// Hand-written Department SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate, repositories hold the SQL.
impl DepartmentRepository {
    /// Create a department.
    ///
    /// RLS scope (ADR-0008), DTO-company pattern: the caller wraps this in
    /// `with_company_scope(Some(company_id))` so the INSERT's WITH CHECK passes under the app role.
    pub async fn insert_department(
        &self,
        pool: &PgPool,
        d: &NewDepartmentRow<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO organization.departments
                    (id, company_id, code, name, parent_id, branch_id, is_group, manager_id, status)
                   VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'active'::org_status)"#,
            )
            .bind(d.id)
            .bind(d.company_id)
            .bind(d.code)
            .bind(d.name)
            .bind(d.parent_id)
            .bind(d.branch_id)
            .bind(d.is_group)
            .bind(d.manager_id),
        )
        .await?;
        Ok(())
    }

    /// The company a department belongs to. `Ok(None)` = no such live department.
    ///
    /// Two callers with two scoping patterns, both supplied by the caller:
    /// - the parent link probe wraps it in `with_company_scope(Some(company_id))` (param-company) and
    ///   keeps its explicit `c != company_id` check as defense-in-depth;
    /// - the repoint owner lookup calls it ID-ONLY — no company argument — so it rides the
    ///   REQUEST-dedicated connection (established by `company_auth`) whose `app.company_id` fences it,
    ///   and another company's department simply is not found.
    pub async fn find_owner_company(
        &self,
        pool: &PgPool,
        department_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                "SELECT company_id FROM organization.departments WHERE id=$1 AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(department_id),
        )
        .await
    }

    /// Re-point a department's invariant-bearing links. The caller has validated them (exist,
    /// same-company, no self-parent) and fences this update to the owning company it read
    /// (`with_company_scope(Some(company_id))`).
    pub async fn repoint(
        &self,
        pool: &PgPool,
        id: Uuid,
        parent_id: Option<Uuid>,
        branch_id: Option<Uuid>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query("UPDATE organization.departments SET parent_id=$2, branch_id=$3 WHERE id=$1")
                .bind(id)
                .bind(parent_id)
                .bind(branch_id),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(DepartmentRepository, Department, soft_delete);
