//! Repository for Department entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Department SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Department, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.
//!
//! RLS LAW (ADR-0029): the module is tenant-agnostic and ships no row fence. Department rows carry
//! no company column — a department's placement is its optional `branch_id` (a branch IS an
//! org-units node), so a department anchored at a branch inherits that branch's place in the tree.
//! Isolation is installed by the COMPOSING service's tenancy decorator.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

// The typed multi-row read twin lives only in the legacy `company_scope` module. Its
// connection discipline is what this repository needs — request-dedicated connection when the
// composing service bound one, plain pool otherwise. The helper's legacy task-local branch is
// never taken: this module sets no legacy scope of its own (ADR-0029).
use backbone_orm::company_scope::fetch_all_scoped;

use crate::domain::entity::Department;

/// Table name for Department entities
pub const TABLE_NAME: &str = "organization.departments";

/// Repository for Department entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct DepartmentRepository(
    backbone_orm::GenericCrudRepository<Department, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for DepartmentRepository {
    type Target = backbone_orm::GenericCrudRepository<Department, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl DepartmentRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated department creation writes.
///
/// Mirrors the raw column shape rather than the `Department` entity. `parent_id`/`branch_id` are
/// expected already link-validated by the caller — existence-only: a link outside the caller's
/// visible scope is simply absent (the composing service's decorator fences the probe,
/// ADR-0029), so a cross-scope link fails closed without a same-company comparison.
pub struct NewDepartmentRow<'a> {
    pub id: Uuid,
    pub code: &'a str,
    pub name: &'a str,
    pub parent_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
    pub is_group: bool,
    pub manager_id: Option<Uuid>,
}

/// Hand-written Department SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate, repositories hold the SQL.
impl DepartmentRepository {
    /// Create a department on the CALLER'S transaction — it commits (or rolls back) as one unit
    /// with the caller's unit of work.
    pub async fn insert_department_on(
        &self,
        conn: &mut sqlx::PgConnection,
        d: &NewDepartmentRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO organization.departments
                (id, code, name, parent_id, branch_id, is_group, manager_id, status)
               VALUES ($1,$2,$3,$4,$5,$6,$7,'active'::org_status)"#,
        )
        .bind(d.id)
        .bind(d.code)
        .bind(d.name)
        .bind(d.parent_id)
        .bind(d.branch_id)
        .bind(d.is_group)
        .bind(d.manager_id)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Whether a live (non-soft-deleted) department exists — the parent-link probe. A department
    /// outside the caller's visible scope is simply absent (the composing service's decorator
    /// fences the read, ADR-0029).
    pub async fn exists_live(
        &self,
        pool: &PgPool,
        department_id: Uuid,
    ) -> Result<bool, sqlx::Error> {
        let row = backbone_orm::org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                "SELECT id FROM organization.departments WHERE id=$1 AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(department_id),
        )
        .await?;
        Ok(row.is_some())
    }

    /// Re-point a department's invariant-bearing links on the CALLER'S transaction. The caller
    /// has validated the links (exist, no self-parent); isolation of the UPDATE itself is the
    /// composing service's decorator (ADR-0029).
    pub async fn repoint_on(
        &self,
        conn: &mut sqlx::PgConnection,
        id: Uuid,
        parent_id: Option<Uuid>,
        branch_id: Option<Uuid>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query("UPDATE organization.departments SET parent_id=$2, branch_id=$3 WHERE id=$1")
            .bind(id)
            .bind(parent_id)
            .bind(branch_id)
            .execute(conn)
            .await?;
        Ok(())
    }
}

/// Lightweight read shape for the department level of the hierarchy endpoint.
/// `status` cast to `::text` so this binds as `String`. Carries `parent_id`
/// (tree) and `branch_id` (placement) so the service can build the forest and
/// group departments under their branch.
#[derive(Debug, sqlx::FromRow, Clone)]
pub struct DepartmentHierarchyRow {
    pub id: Uuid,
    pub code: String,
    pub name: String,
    pub parent_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
    pub level: i32,
    pub is_group: bool,
    pub status: String,
}

/// Hand-written Department SQL for the hierarchy read.
impl DepartmentRepository {
    /// All live (non-soft-deleted) departments anchored at any of `branch_units`, in tree order
    /// (level, then sort_order, then code) so parents precede children.
    ///
    /// Branch membership is the ONLY placement a department has: a department whose `branch_id`
    /// is NULL (the column stays optional) simply does not appear until a branch is assigned.
    /// The caller passes exactly the branch ids it read from its subtree, so a department
    /// attached to a branch outside that subtree is invisible here — fail-closed without a
    /// company comparison (ADR-0029).
    pub async fn list_live_by_units(
        &self,
        pool: &PgPool,
        branch_units: &[Uuid],
    ) -> Result<Vec<DepartmentHierarchyRow>, sqlx::Error> {
        fetch_all_scoped(
            pool,
            sqlx::query_as::<_, DepartmentHierarchyRow>(
                "SELECT id, code, name, parent_id, branch_id, level, is_group, status::text \
                 FROM organization.departments \
                 WHERE branch_id = ANY($1) AND (metadata->>'deleted_at') IS NULL \
                 ORDER BY level, sort_order, code",
            )
            .bind(branch_units),
        )
        .await
    }
}

backbone_core::impl_crud_repository!(DepartmentRepository, Department, soft_delete);
