//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod branch_repository;
mod company_repository;
mod company_industry_repository;
mod department_repository;
mod industry_repository;
mod level_repository;
mod org_unit_repository;
mod position_repository;
mod structure_repository;

// Custom persistence modules
// <<< CUSTOM
// The hand-written validated-write SQL's parameter types (see the three repositories, all declared
// `user_owned` in metaphor.codegen.yaml).
pub use branch_repository::{NewBranchRow, NewHeadOfficeBranchRow};
pub use company_repository::NewCompanyRow;
pub use department_repository::NewDepartmentRow;
// Hierarchy-read row shapes (company/branch/department).
pub use branch_repository::BranchHierarchyRow;
pub use company_repository::CompanyHierarchyRow;
pub use department_repository::DepartmentHierarchyRow;
// END CUSTOM

// Re-exports
pub use branch_repository::BranchRepository;
pub use company_repository::CompanyRepository;
pub use company_industry_repository::CompanyIndustryRepository;
pub use department_repository::DepartmentRepository;
pub use industry_repository::IndustryRepository;
pub use level_repository::LevelRepository;
pub use org_unit_repository::OrgUnitRepository;
pub use position_repository::PositionRepository;
pub use structure_repository::StructureRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// Re-bind the caller's ambient org scope onto a transaction opened on the plain pool — the
// scope is task-local and a fresh pool transaction carries none of it. With no ambient scope
// (standalone deployment, onboarding, jobs) the transaction stays plain: the module is
// tenant-agnostic and the composing service's tenancy decorator owns isolation (ADR-0029).
// Same convention as the backbone-pos / backbone-promo / backbone-livechat write paths.
pub(crate) async fn relay_ambient_scope(conn: &mut sqlx::PgConnection) -> Result<(), sqlx::Error> {
    if let Some(scope) = backbone_orm::org_scope::current_org_scope() {
        backbone_orm::org_scope::bind_org_scope_on(conn, &scope).await?;
    }
    Ok(())
}
// END CUSTOM
