//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod branch_repository;
mod company_repository;
mod company_industry_repository;
mod department_repository;
mod industry_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use branch_repository::BranchRepository;
pub use company_repository::CompanyRepository;
pub use company_industry_repository::CompanyIndustryRepository;
pub use department_repository::DepartmentRepository;
pub use industry_repository::IndustryRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// The hand-written validated-write SQL's parameter types (see the three repositories, all declared
// `user_owned` in metaphor.codegen.yaml).
pub use branch_repository::{NewBranchRow, NewHeadOfficeBranchRow};
pub use company_repository::NewCompanyRow;
pub use department_repository::NewDepartmentRow;
// END CUSTOM