//! Repository for Position entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Position, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Position;

/// Table name for Position entities
pub const TABLE_NAME: &str = "organization.positions";

/// Repository for Position entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PositionRepository(
    backbone_orm::GenericCrudRepository<Position, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PositionRepository {
    type Target = backbone_orm::GenericCrudRepository<Position, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PositionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PositionRepository, Position, soft_delete);
