//! Repository for Structure entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Structure, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Structure;

/// Table name for Structure entities
pub const TABLE_NAME: &str = "organization.structures";

/// Repository for Structure entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct StructureRepository(
    backbone_orm::GenericCrudRepository<Structure, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for StructureRepository {
    type Target = backbone_orm::GenericCrudRepository<Structure, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl StructureRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(StructureRepository, Structure, soft_delete);
