//! Validator for Branch entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Branch>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Branch;

/// Validator type alias for Branch entities.
pub type BranchValidator = EntityValidator<Branch>;

/// Build a validator for Branch with all schema-defined field rules.
pub fn branch_validator() -> BranchValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &Branch| &e.code))
        .rule(RequiredString::new("name", |e: &Branch| &e.name))
        .rule(OptionalNotBlank::new("npwp", |e: &Branch| e.npwp.as_deref()))
        .rule(OptionalNotBlank::new("email", |e: &Branch| e.email.as_deref()))
        .rule(OptionalNotBlank::new("phone", |e: &Branch| e.phone.as_deref()))
        .rule(OptionalNotBlank::new("address", |e: &Branch| e.address.as_deref()))
        .rule(OptionalNotBlank::new("city", |e: &Branch| e.city.as_deref()))
        .rule(OptionalNotBlank::new("province", |e: &Branch| e.province.as_deref()))
        .rule(OptionalNotBlank::new("postal_code", |e: &Branch| e.postal_code.as_deref()))
        .rule(RequiredString::new("country", |e: &Branch| &e.country))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
