//! Validator for Company entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Company>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::Company;

/// Validator type alias for Company entities.
pub type CompanyValidator = EntityValidator<Company>;

/// Build a validator for Company with all schema-defined field rules.
pub fn company_validator() -> CompanyValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &Company| &e.code))
        .rule(RequiredString::new("legal_name", |e: &Company| &e.legal_name))
        .rule(OptionalNotBlank::new("trade_name", |e: &Company| e.trade_name.as_deref()))
        .rule(OptionalNotBlank::new("npwp", |e: &Company| e.npwp.as_deref()))
        .rule(OptionalNotBlank::new("nib", |e: &Company| e.nib.as_deref()))
        .rule(RequiredString::new("base_currency", |e: &Company| &e.base_currency))
        .rule(NonNegative::new("fiscal_year_start_month", |e: &Company| e.fiscal_year_start_month as i64))
        .rule(OptionalNotBlank::new("email", |e: &Company| e.email.as_deref()))
        .rule(OptionalNotBlank::new("phone", |e: &Company| e.phone.as_deref()))
        .rule(OptionalNotBlank::new("address", |e: &Company| e.address.as_deref()))
        .rule(OptionalNotBlank::new("city", |e: &Company| e.city.as_deref()))
        .rule(OptionalNotBlank::new("province", |e: &Company| e.province.as_deref()))
        .rule(OptionalNotBlank::new("postal_code", |e: &Company| e.postal_code.as_deref()))
        .rule(RequiredString::new("country", |e: &Company| &e.country))
        .rule(OptionalNotBlank::new("notes", |e: &Company| e.notes.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
