//! Validator for CompanyIndustry entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CompanyIndustry>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::CompanyIndustry;

/// Validator type alias for CompanyIndustry entities.
pub type CompanyIndustryValidator = EntityValidator<CompanyIndustry>;

/// Build a validator for CompanyIndustry with all schema-defined field rules.
pub fn company_industry_validator() -> CompanyIndustryValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
