//! Validator for Department entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Department>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::Department;

/// Validator type alias for Department entities.
pub type DepartmentValidator = EntityValidator<Department>;

/// Build a validator for Department with all schema-defined field rules.
pub fn department_validator() -> DepartmentValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &Department| &e.code))
        .rule(RequiredString::new("name", |e: &Department| &e.name))
        .rule(NonNegative::new("level", |e: &Department| e.level as i64))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
