//! Validator for Industry entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Industry>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::Industry;

/// Validator type alias for Industry entities.
pub type IndustryValidator = EntityValidator<Industry>;

/// Build a validator for Industry with all schema-defined field rules.
pub fn industry_validator() -> IndustryValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &Industry| &e.code))
        .rule(RequiredString::new("name", |e: &Industry| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
