//! Validator for Level entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Level>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Level;

/// Validator type alias for Level entities.
pub type LevelValidator = EntityValidator<Level>;

/// Build a validator for Level with all schema-defined field rules.
pub fn level_validator() -> LevelValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Level| &e.name))
        .rule(OptionalNotBlank::new("grade", |e: &Level| e.grade.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
