//! Validator for OrgUnit entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<OrgUnit>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::OrgUnit;

/// Validator type alias for OrgUnit entities.
pub type OrgUnitValidator = EntityValidator<OrgUnit>;

/// Build a validator for OrgUnit with all schema-defined field rules.
pub fn org_unit_validator() -> OrgUnitValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("code", |e: &OrgUnit| e.code.as_deref()))
        .rule(RequiredString::new("name", |e: &OrgUnit| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
