//! Validator for Structure entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Structure>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::Structure;

/// Validator type alias for Structure entities.
pub type StructureValidator = EntityValidator<Structure>;

/// Build a validator for Structure with all schema-defined field rules.
pub fn structure_validator() -> StructureValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Structure| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
