//! Auth configuration for Branch handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Branch>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::BranchService;
use crate::domain::entity::Branch;

/// Permission string constants for Branch operations.
pub mod permissions {
    pub const LIST:        &str = "branch:list";
    pub const READ:        &str = "branch:read";
    pub const CREATE:      &str = "branch:create";
    pub const UPDATE:      &str = "branch:update";
    pub const DELETE:      &str = "branch:delete";
    pub const RESTORE:     &str = "branch:restore";
    pub const TRASH:       &str = "branch:trash";
    pub const EMPTY_TRASH: &str = "branch:empty_trash";
    pub const BULK_CREATE: &str = "branch:bulk_create";
    pub const UPSERT:      &str = "branch:upsert";
}

/// Resource policy for Branch — maps CRUD actions to permission strings.
pub struct BranchPolicy;

#[async_trait]
impl ResourcePolicy<Branch> for BranchPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Branch,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Branch handlers.
///
/// Wraps `BranchService` and checks `BranchPolicy` before delegating.
pub type BranchGuard = PermissionGuard<Branch>;

/// Service-integrated permission guard for Branch (for use in generated handlers).
pub type BranchServiceGuard = ServicePermissionGuard<Branch, BranchService, BranchPolicy>;

// <<< CUSTOM
// END CUSTOM
