//! Auth configuration for CompanyIndustry handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<CompanyIndustry>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CompanyIndustryService;
use crate::domain::entity::CompanyIndustry;

/// Permission string constants for CompanyIndustry operations.
pub mod permissions {
    pub const LIST:        &str = "company_industry:list";
    pub const READ:        &str = "company_industry:read";
    pub const CREATE:      &str = "company_industry:create";
    pub const UPDATE:      &str = "company_industry:update";
    pub const DELETE:      &str = "company_industry:delete";
    pub const RESTORE:     &str = "company_industry:restore";
    pub const TRASH:       &str = "company_industry:trash";
    pub const EMPTY_TRASH: &str = "company_industry:empty_trash";
    pub const BULK_CREATE: &str = "company_industry:bulk_create";
    pub const UPSERT:      &str = "company_industry:upsert";
}

/// Resource policy for CompanyIndustry — maps CRUD actions to permission strings.
pub struct CompanyIndustryPolicy;

#[async_trait]
impl ResourcePolicy<CompanyIndustry> for CompanyIndustryPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &CompanyIndustry,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for CompanyIndustry handlers.
///
/// Wraps `CompanyIndustryService` and checks `CompanyIndustryPolicy` before delegating.
pub type CompanyIndustryGuard = PermissionGuard<CompanyIndustry>;

/// Service-integrated permission guard for CompanyIndustry (for use in generated handlers).
pub type CompanyIndustryServiceGuard = ServicePermissionGuard<CompanyIndustry, CompanyIndustryService, CompanyIndustryPolicy>;

// <<< CUSTOM
// END CUSTOM
