//! Auth configuration for Company handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Company>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CompanyService;
use crate::domain::entity::Company;

/// Permission string constants for Company operations.
pub mod permissions {
    pub const LIST:        &str = "company:list";
    pub const READ:        &str = "company:read";
    pub const CREATE:      &str = "company:create";
    pub const UPDATE:      &str = "company:update";
    pub const DELETE:      &str = "company:delete";
    pub const RESTORE:     &str = "company:restore";
    pub const TRASH:       &str = "company:trash";
    pub const EMPTY_TRASH: &str = "company:empty_trash";
    pub const BULK_CREATE: &str = "company:bulk_create";
    pub const UPSERT:      &str = "company:upsert";
}

/// Resource policy for Company — maps CRUD actions to permission strings.
pub struct CompanyPolicy;

#[async_trait]
impl ResourcePolicy<Company> for CompanyPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Company,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Company handlers.
///
/// Wraps `CompanyService` and checks `CompanyPolicy` before delegating.
pub type CompanyGuard = PermissionGuard<Company>;

/// Service-integrated permission guard for Company (for use in generated handlers).
pub type CompanyServiceGuard = ServicePermissionGuard<Company, CompanyService, CompanyPolicy>;

// <<< CUSTOM
// END CUSTOM
