//! Auth configuration for Department handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Department>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::DepartmentService;
use crate::domain::entity::Department;

/// Permission string constants for Department operations.
pub mod permissions {
    pub const LIST:        &str = "department:list";
    pub const READ:        &str = "department:read";
    pub const CREATE:      &str = "department:create";
    pub const UPDATE:      &str = "department:update";
    pub const DELETE:      &str = "department:delete";
    pub const RESTORE:     &str = "department:restore";
    pub const TRASH:       &str = "department:trash";
    pub const EMPTY_TRASH: &str = "department:empty_trash";
    pub const BULK_CREATE: &str = "department:bulk_create";
    pub const UPSERT:      &str = "department:upsert";
}

/// Resource policy for Department — maps CRUD actions to permission strings.
pub struct DepartmentPolicy;

#[async_trait]
impl ResourcePolicy<Department> for DepartmentPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Department,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Department handlers.
///
/// Wraps `DepartmentService` and checks `DepartmentPolicy` before delegating.
pub type DepartmentGuard = PermissionGuard<Department>;

/// Service-integrated permission guard for Department (for use in generated handlers).
pub type DepartmentServiceGuard = ServicePermissionGuard<Department, DepartmentService, DepartmentPolicy>;

// <<< CUSTOM
// END CUSTOM
