//! Auth configuration for Industry handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Industry>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::IndustryService;
use crate::domain::entity::Industry;

/// Permission string constants for Industry operations.
pub mod permissions {
    pub const LIST:        &str = "industry:list";
    pub const READ:        &str = "industry:read";
    pub const CREATE:      &str = "industry:create";
    pub const UPDATE:      &str = "industry:update";
    pub const DELETE:      &str = "industry:delete";
    pub const RESTORE:     &str = "industry:restore";
    pub const TRASH:       &str = "industry:trash";
    pub const EMPTY_TRASH: &str = "industry:empty_trash";
    pub const BULK_CREATE: &str = "industry:bulk_create";
    pub const UPSERT:      &str = "industry:upsert";
}

/// Resource policy for Industry — maps CRUD actions to permission strings.
pub struct IndustryPolicy;

#[async_trait]
impl ResourcePolicy<Industry> for IndustryPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Industry,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Industry handlers.
///
/// Wraps `IndustryService` and checks `IndustryPolicy` before delegating.
pub type IndustryGuard = PermissionGuard<Industry>;

/// Service-integrated permission guard for Industry (for use in generated handlers).
pub type IndustryServiceGuard = ServicePermissionGuard<Industry, IndustryService, IndustryPolicy>;

// <<< CUSTOM
// END CUSTOM
