//! Auth configuration for Level handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Level>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::LevelService;
use crate::domain::entity::Level;

/// Permission string constants for Level operations.
pub mod permissions {
    pub const LIST:        &str = "level:list";
    pub const READ:        &str = "level:read";
    pub const CREATE:      &str = "level:create";
    pub const UPDATE:      &str = "level:update";
    pub const DELETE:      &str = "level:delete";
    pub const RESTORE:     &str = "level:restore";
    pub const TRASH:       &str = "level:trash";
    pub const EMPTY_TRASH: &str = "level:empty_trash";
    pub const BULK_CREATE: &str = "level:bulk_create";
    pub const UPSERT:      &str = "level:upsert";
}

/// Resource policy for Level — maps CRUD actions to permission strings.
pub struct LevelPolicy;

#[async_trait]
impl ResourcePolicy<Level> for LevelPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Level,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Level handlers.
///
/// Wraps `LevelService` and checks `LevelPolicy` before delegating.
pub type LevelGuard = PermissionGuard<Level>;

/// Service-integrated permission guard for Level (for use in generated handlers).
pub type LevelServiceGuard = ServicePermissionGuard<Level, LevelService, LevelPolicy>;

// <<< CUSTOM
// END CUSTOM
