//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod branch_auth;
pub mod company_auth;
pub mod department_auth;

pub use branch_auth::{BranchPolicy, BranchGuard, BranchServiceGuard};
pub use company_auth::{CompanyPolicy, CompanyGuard, CompanyServiceGuard};
pub use department_auth::{DepartmentPolicy, DepartmentGuard, DepartmentServiceGuard};

// <<< CUSTOM
// END CUSTOM
