//! Auth configuration for Position handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Position>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PositionService;
use crate::domain::entity::Position;

/// Permission string constants for Position operations.
pub mod permissions {
    pub const LIST:        &str = "position:list";
    pub const READ:        &str = "position:read";
    pub const CREATE:      &str = "position:create";
    pub const UPDATE:      &str = "position:update";
    pub const DELETE:      &str = "position:delete";
    pub const RESTORE:     &str = "position:restore";
    pub const TRASH:       &str = "position:trash";
    pub const EMPTY_TRASH: &str = "position:empty_trash";
    pub const BULK_CREATE: &str = "position:bulk_create";
    pub const UPSERT:      &str = "position:upsert";
}

/// Resource policy for Position — maps CRUD actions to permission strings.
pub struct PositionPolicy;

#[async_trait]
impl ResourcePolicy<Position> for PositionPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Position,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Position handlers.
///
/// Wraps `PositionService` and checks `PositionPolicy` before delegating.
pub type PositionGuard = PermissionGuard<Position>;

/// Service-integrated permission guard for Position (for use in generated handlers).
pub type PositionServiceGuard = ServicePermissionGuard<Position, PositionService, PositionPolicy>;

// <<< CUSTOM
// END CUSTOM
