//! Auth configuration for Structure handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Structure>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::StructureService;
use crate::domain::entity::Structure;

/// Permission string constants for Structure operations.
pub mod permissions {
    pub const LIST:        &str = "structure:list";
    pub const READ:        &str = "structure:read";
    pub const CREATE:      &str = "structure:create";
    pub const UPDATE:      &str = "structure:update";
    pub const DELETE:      &str = "structure:delete";
    pub const RESTORE:     &str = "structure:restore";
    pub const TRASH:       &str = "structure:trash";
    pub const EMPTY_TRASH: &str = "structure:empty_trash";
    pub const BULK_CREATE: &str = "structure:bulk_create";
    pub const UPSERT:      &str = "structure:upsert";
}

/// Resource policy for Structure — maps CRUD actions to permission strings.
pub struct StructurePolicy;

#[async_trait]
impl ResourcePolicy<Structure> for StructurePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Structure,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Structure handlers.
///
/// Wraps `StructureService` and checks `StructurePolicy` before delegating.
pub type StructureGuard = PermissionGuard<Structure>;

/// Service-integrated permission guard for Structure (for use in generated handlers).
pub type StructureServiceGuard = ServicePermissionGuard<Structure, StructureService, StructurePolicy>;

// <<< CUSTOM
// END CUSTOM
