//! Branch API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Branch CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// BRANCH TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Branch
pub struct BranchTestData;

impl TestDataGenerator for BranchTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "branch_type": "head_office",
            "is_head_office": false,
            "npwp": null,
            "email": null,
            "phone": null,
            "address": null,
            "city": null,
            "province": null,
            "postal_code": null,
            "country": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "branch_type": "head_office",
            "is_head_office": false,
            "npwp": null,
            "email": null,
            "phone": null,
            "address": null,
            "city": null,
            "province": null,
            "postal_code": null,
            "country": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/companies", &super::company_api_test::CompanyTestData).await {
            deps.push(("company_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// BRANCH API TEST
// ============================================================================

/// Branch API test suite
pub struct BranchApiTest {
    inner: GenericCrudTest<BranchTestData>,
}

impl BranchApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/branches", "Branch");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, BranchTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for BranchApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_branch_crud() {
        let mut test = BranchApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Branch specific tests here
// <<< CUSTOM TESTS END >>>
