//! Department API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Department CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// DEPARTMENT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Department
pub struct DepartmentTestData;

impl TestDataGenerator for DepartmentTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "parent_id": null,
            "level": 1,
            "is_group": false,
            "branch_id": null,
            "manager_id": null,
            "sort_order": 1,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "parent_id": null,
            "level": 1,
            "is_group": false,
            "branch_id": null,
            "manager_id": null,
            "sort_order": 1,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/companies", &super::company_api_test::CompanyTestData).await {
            deps.push(("company_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// DEPARTMENT API TEST
// ============================================================================

/// Department API test suite
pub struct DepartmentApiTest {
    inner: GenericCrudTest<DepartmentTestData>,
}

impl DepartmentApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/departments", "Department");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, DepartmentTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for DepartmentApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_department_crud() {
        let mut test = DepartmentApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Department specific tests here
// <<< CUSTOM TESTS END >>>
