//! OrgUnit API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the OrgUnit CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ORGUNIT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for OrgUnit
pub struct OrgUnitTestData;

impl TestDataGenerator for OrgUnitTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "kind": "root",
            "parent_id": null,
            "code": null,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "kind": "root",
            "parent_id": null,
            "code": null,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ORGUNIT API TEST
// ============================================================================

/// OrgUnit API test suite
pub struct OrgUnitApiTest {
    inner: GenericCrudTest<OrgUnitTestData>,
}

impl OrgUnitApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/org_units", "OrgUnit");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, OrgUnitTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for OrgUnitApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_org_unit_crud() {
        let mut test = OrgUnitApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add OrgUnit specific tests here
// <<< CUSTOM TESTS END >>>
