//! Organization Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::BranchService;
use crate::application::service::CompanyService;
use crate::application::service::DepartmentService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Branch service
    pub branch_service: Arc<BranchService>,
    /// Company service
    pub company_service: Arc<CompanyService>,
    /// Department service
    pub department_service: Arc<DepartmentService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        branch_service: Arc<BranchService>,
        company_service: Arc<CompanyService>,
        department_service: Arc<DepartmentService>
    ) -> Self {
        Self {
            branch_service,
            company_service,
            department_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::OrganizationModule) -> Self {
        Self {
            branch_service: module.branch_service.clone(),
            company_service: module.company_service.clone(),
            department_service: module.department_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    branch_service: Option<Arc<BranchService>>,
    company_service: Option<Arc<CompanyService>>,
    department_service: Option<Arc<DepartmentService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Branch service.
    pub fn with_branch_service(mut self, service: Arc<BranchService>) -> Self {
        self.branch_service = Some(service);
        self
    }

    /// Set the Company service.
    pub fn with_company_service(mut self, service: Arc<CompanyService>) -> Self {
        self.company_service = Some(service);
        self
    }

    /// Set the Department service.
    pub fn with_department_service(mut self, service: Arc<DepartmentService>) -> Self {
        self.department_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            branch_service: self.branch_service.expect("branch_service is required"),
            company_service: self.company_service.expect("company_service is required"),
            department_service: self.department_service.expect("department_service is required"),
        }
    }
}
