//! CompanyOnboarding flow implementation
//!
//! Generated by metaphor-schema
//!
//! Bring a new legal entity onto the platform atomically:
//! - validate NPWP format (15/16 digits) before any write
//! - fast pre-check on company code uniqueness (the partial unique index is the real arbiter)
//! - in one transaction: create the Company, then its head-office Branch
//! - a company is never born without a head office
//! On a unique violation the constraint name distinguishes duplicate_company_code vs duplicate_npwp.

use serde::{Deserialize, Serialize};
use std::sync::Arc;
use chrono;
use backbone_core::flow::{WorkflowStep, WorkflowContext};

/// Error type for flow execution
#[derive(Debug, Clone, thiserror::Error)]
pub enum FlowError {
    #[error("No current step to execute")]
    NoCurrentStep,

    #[error("Step execution failed: {0}")]
    StepFailed(String),

    #[error("Condition evaluation failed: {0}")]
    ConditionFailed(String),

    #[error("Compensation failed: {0}")]
    CompensationFailed(String),

    #[error("Flow timed out")]
    Timeout,

    #[error("Flow cancelled")]
    Cancelled,

    #[error("Invalid state transition: {from} -> {to}")]
    InvalidTransition { from: String, to: String },
}

/// Execution status for CompanyOnboarding flow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CompanyOnboardingFlowStatus {
    /// Flow is pending execution
    Pending,
    /// Flow is currently running
    Running,
    /// Flow is waiting for an event or condition
    Waiting,
    /// Flow completed successfully
    Completed,
    /// Flow failed
    Failed,
    /// Flow was cancelled
    Cancelled,
    /// Flow is compensating (rolling back)
    Compensating,
}

/// Steps in CompanyOnboarding flow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CompanyOnboardingFlowStep {
    /// validate_npwp
    ValidateNpwp,
    /// check_code_unique
    CheckCodeUnique,
    /// write_company
    WriteCompany,
    /// write_head_office_branch
    WriteHeadOfficeBranch,
    /// onboarded
    Onboarded,
    /// rejected_invalid_npwp
    RejectedInvalidNpwp,
    /// rejected_duplicate
    RejectedDuplicate,
}

/// Instance of CompanyOnboarding flow execution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompanyOnboardingFlowInstance {
    /// Unique instance ID
    pub id: String,
    /// Current status
    pub status: CompanyOnboardingFlowStatus,
    /// Current step
    pub current_step: Option<CompanyOnboardingFlowStep>,
    /// Flow context (variables)
    pub context: serde_json::Value,
    /// Completed steps
    pub completed_steps: Vec<CompanyOnboardingFlowStep>,
    /// Error if failed
    pub error: Option<String>,
    /// Created timestamp
    pub created_at: chrono::DateTime<chrono::Utc>,
    /// Updated timestamp
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

impl CompanyOnboardingFlowInstance {
    /// Create a new flow instance
    pub fn new(id: impl Into<String>) -> Self {
        let now = chrono::Utc::now();
        Self {
            id: id.into(),
            status: CompanyOnboardingFlowStatus::Pending,
            current_step: None,
            context: serde_json::json!({}),
            completed_steps: Vec::new(),
            error: None,
            created_at: now,
            updated_at: now,
        }
    }

    /// Check if flow is complete
    pub fn is_complete(&self) -> bool {
        matches!(
            self.status,
            CompanyOnboardingFlowStatus::Completed | CompanyOnboardingFlowStatus::Failed | CompanyOnboardingFlowStatus::Cancelled
        )
    }

    /// Check if flow is running
    pub fn is_running(&self) -> bool {
        matches!(
            self.status,
            CompanyOnboardingFlowStatus::Running | CompanyOnboardingFlowStatus::Waiting
        )
    }

    /// Set a context variable
    pub fn set_context(&mut self, key: &str, value: serde_json::Value) {
        if let serde_json::Value::Object(ref mut map) = self.context {
            map.insert(key.to_string(), value);
        }
        self.updated_at = chrono::Utc::now();
    }

    /// Get a context variable
    pub fn get_context(&self, key: &str) -> Option<&serde_json::Value> {
        if let serde_json::Value::Object(ref map) = self.context {
            map.get(key)
        } else {
            None
        }
    }
}

// Phase 1: FlowInstance satisfies backbone_core::flow::WorkflowContext.
// The entity() accessor requires the entity to be carried in the instance;
// add `pub entity: CompanyOnboarding` in the // <<< CUSTOM section and remove the todo!.
#[allow(unused_variables)]
impl WorkflowContext<CompanyOnboardingFlowInstance> for CompanyOnboardingFlowInstance {
    fn entity(&self) -> &CompanyOnboardingFlowInstance { self }
    fn set_var(&mut self, key: &str, value: serde_json::Value) {
        self.set_context(key, value);
    }
    fn get_var(&self, key: &str) -> Option<&serde_json::Value> {
        self.get_context(key)
    }
}

/// Step handler trait for CompanyOnboarding flow
#[async_trait::async_trait]
pub trait CompanyOnboardingStepHandler: Send + Sync {
    /// Handle validate_npwp step
    async fn handle_validate_npwp(
        &self,
        instance: &mut CompanyOnboardingFlowInstance,
    ) -> Result<Option<CompanyOnboardingFlowStep>, FlowError>;

    /// Handle check_code_unique step
    async fn handle_check_code_unique(
        &self,
        instance: &mut CompanyOnboardingFlowInstance,
    ) -> Result<Option<CompanyOnboardingFlowStep>, FlowError>;

    /// Handle write_company step
    async fn handle_write_company(
        &self,
        instance: &mut CompanyOnboardingFlowInstance,
    ) -> Result<Option<CompanyOnboardingFlowStep>, FlowError>;

    /// Handle write_head_office_branch step
    async fn handle_write_head_office_branch(
        &self,
        instance: &mut CompanyOnboardingFlowInstance,
    ) -> Result<Option<CompanyOnboardingFlowStep>, FlowError>;

    /// Handle terminal step onboarded
    async fn handle_onboarded(
        &self,
        instance: &mut CompanyOnboardingFlowInstance,
    ) -> Result<(), FlowError>;

    /// Handle terminal step rejected_invalid_npwp
    async fn handle_rejected_invalid_npwp(
        &self,
        instance: &mut CompanyOnboardingFlowInstance,
    ) -> Result<(), FlowError>;

    /// Handle terminal step rejected_duplicate
    async fn handle_rejected_duplicate(
        &self,
        instance: &mut CompanyOnboardingFlowInstance,
    ) -> Result<(), FlowError>;

}

/// Executor for CompanyOnboarding flow
pub struct CompanyOnboardingFlowExecutor<H: CompanyOnboardingStepHandler> {
    handler: Arc<H>,
}

impl<H: CompanyOnboardingStepHandler> CompanyOnboardingFlowExecutor<H> {
    /// Create a new flow executor
    pub fn new(handler: Arc<H>) -> Self {
        Self { handler }
    }

    /// Start a new flow instance
    pub async fn start(&self, instance_id: impl Into<String>) -> Result<CompanyOnboardingFlowInstance, FlowError> {
        let mut instance = CompanyOnboardingFlowInstance::new(instance_id);
        instance.status = CompanyOnboardingFlowStatus::Running;
        instance.current_step = Some(CompanyOnboardingFlowStep::ValidateNpwp);
        Ok(instance)
    }

    /// Execute the current step
    pub async fn execute_step(&self, instance: &mut CompanyOnboardingFlowInstance) -> Result<(), FlowError> {
        let current_step = match instance.current_step {
            Some(step) => step,
            None => return Err(FlowError::NoCurrentStep),
        };

        let next_step = match current_step {
            CompanyOnboardingFlowStep::ValidateNpwp => {
                self.handler.handle_validate_npwp(instance).await?
            }
            CompanyOnboardingFlowStep::CheckCodeUnique => {
                self.handler.handle_check_code_unique(instance).await?
            }
            CompanyOnboardingFlowStep::WriteCompany => {
                self.handler.handle_write_company(instance).await?
            }
            CompanyOnboardingFlowStep::WriteHeadOfficeBranch => {
                self.handler.handle_write_head_office_branch(instance).await?
            }
            CompanyOnboardingFlowStep::Onboarded => {
                self.handler.handle_onboarded(instance).await?;
                None // Terminal step
            }
            CompanyOnboardingFlowStep::RejectedInvalidNpwp => {
                self.handler.handle_rejected_invalid_npwp(instance).await?;
                None // Terminal step
            }
            CompanyOnboardingFlowStep::RejectedDuplicate => {
                self.handler.handle_rejected_duplicate(instance).await?;
                None // Terminal step
            }
        };

        // Mark current step as completed
        instance.completed_steps.push(current_step);

        // Move to next step
        match next_step {
            Some(next) => {
                instance.current_step = Some(next);
            }
            None => {
                instance.current_step = None;
                instance.status = CompanyOnboardingFlowStatus::Completed;
            }
        }

        instance.updated_at = chrono::Utc::now();
        Ok(())
    }

    /// Run the flow to completion
    pub async fn run(&self, instance: &mut CompanyOnboardingFlowInstance) -> Result<(), FlowError> {
        while !instance.is_complete() && instance.status != CompanyOnboardingFlowStatus::Waiting {
            self.execute_step(instance).await?;
        }
        Ok(())
    }

    /// Cancel the flow
    pub fn cancel(&self, instance: &mut CompanyOnboardingFlowInstance) {
        instance.status = CompanyOnboardingFlowStatus::Cancelled;
        instance.updated_at = chrono::Utc::now();
    }

    /// Mark flow as failed
    pub fn fail(&self, instance: &mut CompanyOnboardingFlowInstance, error: impl Into<String>) {
        instance.status = CompanyOnboardingFlowStatus::Failed;
        instance.error = Some(error.into());
        instance.updated_at = chrono::Utc::now();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_flow_instance_creation() {
        let instance = CompanyOnboardingFlowInstance::new("test-1");
        assert_eq!(instance.id, "test-1");
        assert_eq!(instance.status, CompanyOnboardingFlowStatus::Pending);
        assert!(!instance.is_complete());
    }

    #[test]
    fn test_flow_context() {
        let mut instance = CompanyOnboardingFlowInstance::new("test-2");
        instance.set_context("key", serde_json::json!("value"));
        let value = instance.get_context("key");
        assert_eq!(value, Some(&serde_json::json!("value")));
    }

    #[test]
    fn test_flow_status_transitions() {
        let mut instance = CompanyOnboardingFlowInstance::new("test-3");
        assert!(!instance.is_running());

        instance.status = CompanyOnboardingFlowStatus::Running;
        assert!(instance.is_running());
        assert!(!instance.is_complete());

        instance.status = CompanyOnboardingFlowStatus::Completed;
        assert!(instance.is_complete());
        assert!(!instance.is_running());
    }
}