//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    branch_handler::create_branch_routes,
    company_handler::create_company_routes,
    company_industry_handler::create_company_industry_routes,
    department_handler::create_department_routes,
    industry_handler::create_industry_routes,
};

use crate::application::service::{
    BranchService,
    CompanyService,
    CompanyIndustryService,
    DepartmentService,
    IndustryService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub branch: Arc<BranchService>,
    pub company: Arc<CompanyService>,
    pub company_industry: Arc<CompanyIndustryService>,
    pub department: Arc<DepartmentService>,
    pub industry: Arc<IndustryService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Branch routes (12 Backbone endpoints)
        .merge(create_branch_routes(services.branch))
        // Company routes (12 Backbone endpoints)
        .merge(create_company_routes(services.company))
        // CompanyIndustry routes (12 Backbone endpoints)
        .merge(create_company_industry_routes(services.company_industry))
        // Department routes (12 Backbone endpoints)
        .merge(create_department_routes(services.department))
        // Industry routes (12 Backbone endpoints)
        .merge(create_industry_routes(services.industry))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn branch_routes(service: Arc<BranchService>) -> Router {
        create_branch_routes(service)
    }

    pub fn company_routes(service: Arc<CompanyService>) -> Router {
        create_company_routes(service)
    }

    pub fn company_industry_routes(service: Arc<CompanyIndustryService>) -> Router {
        create_company_industry_routes(service)
    }

    pub fn department_routes(service: Arc<DepartmentService>) -> Router {
        create_department_routes(service)
    }

    pub fn industry_routes(service: Arc<IndustryService>) -> Router {
        create_industry_routes(service)
    }

}
