//! Public events for Organization module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// BRANCH EVENTS
// ============================================================================

/// Event published when a Branch is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BranchCreatedEvent {
    pub id: BranchId,
    pub data: BranchDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Branch is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BranchUpdatedEvent {
    pub id: BranchId,
    pub data: BranchDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Branch is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BranchDeletedEvent {
    pub id: BranchId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// COMPANY EVENTS
// ============================================================================

/// Event published when a Company is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompanyCreatedEvent {
    pub id: CompanyId,
    pub data: CompanyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Company is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompanyUpdatedEvent {
    pub id: CompanyId,
    pub data: CompanyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Company is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompanyDeletedEvent {
    pub id: CompanyId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// COMPANYINDUSTRY EVENTS
// ============================================================================

/// Event published when a CompanyIndustry is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompanyIndustryCreatedEvent {
    pub id: CompanyIndustryId,
    pub data: CompanyIndustryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CompanyIndustry is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompanyIndustryUpdatedEvent {
    pub id: CompanyIndustryId,
    pub data: CompanyIndustryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CompanyIndustry is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompanyIndustryDeletedEvent {
    pub id: CompanyIndustryId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// DEPARTMENT EVENTS
// ============================================================================

/// Event published when a Department is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DepartmentCreatedEvent {
    pub id: DepartmentId,
    pub data: DepartmentDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Department is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DepartmentUpdatedEvent {
    pub id: DepartmentId,
    pub data: DepartmentDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Department is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DepartmentDeletedEvent {
    pub id: DepartmentId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// INDUSTRY EVENTS
// ============================================================================

/// Event published when a Industry is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IndustryCreatedEvent {
    pub id: IndustryId,
    pub data: IndustryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Industry is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IndustryUpdatedEvent {
    pub id: IndustryId,
    pub data: IndustryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Industry is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IndustryDeletedEvent {
    pub id: IndustryId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Organization module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum OrganizationEvent {
    BranchCreated(BranchCreatedEvent),
    BranchUpdated(BranchUpdatedEvent),
    BranchDeleted(BranchDeletedEvent),
    CompanyCreated(CompanyCreatedEvent),
    CompanyUpdated(CompanyUpdatedEvent),
    CompanyDeleted(CompanyDeletedEvent),
    CompanyIndustryCreated(CompanyIndustryCreatedEvent),
    CompanyIndustryUpdated(CompanyIndustryUpdatedEvent),
    CompanyIndustryDeleted(CompanyIndustryDeletedEvent),
    DepartmentCreated(DepartmentCreatedEvent),
    DepartmentUpdated(DepartmentUpdatedEvent),
    DepartmentDeleted(DepartmentDeletedEvent),
    IndustryCreated(IndustryCreatedEvent),
    IndustryUpdated(IndustryUpdatedEvent),
    IndustryDeleted(IndustryDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrganizationEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for OrganizationEventMetadata {
    fn default() -> Self {
        Self {
            module: "organization",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
