//! Organization Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Organization exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use organization::exports::{BranchDto, OrganizationQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `BranchDto` - Data transfer object for Branch
/// - `BranchSummary` - Summary view of Branch
/// - `BranchId` - Type-safe ID wrapper
/// - `CompanyDto` - Data transfer object for Company
/// - `CompanySummary` - Summary view of Company
/// - `CompanyId` - Type-safe ID wrapper
/// - `DepartmentDto` - Data transfer object for Department
/// - `DepartmentSummary` - Summary view of Department
/// - `DepartmentId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `OrganizationQueryService` - Read-only queries
///
/// ## Public Events
/// - `BranchCreatedEvent` - Published when Branch is created
/// - `BranchUpdatedEvent` - Published when Branch is updated
/// - `BranchDeletedEvent` - Published when Branch is deleted
/// - `CompanyCreatedEvent` - Published when Company is created
/// - `CompanyUpdatedEvent` - Published when Company is updated
/// - `CompanyDeletedEvent` - Published when Company is deleted
/// - `DepartmentCreatedEvent` - Published when Department is created
/// - `DepartmentUpdatedEvent` - Published when Department is updated
/// - `DepartmentDeletedEvent` - Published when Department is deleted
pub struct ExportSummary;
