//! Public services for Organization module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Organization module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait OrganizationQueryService: Send + Sync {
    /// Get Branch by ID
    async fn get_branch(&self, id: BranchId) -> Result<Option<BranchDto>>;

    /// Get Branch summary by ID
    async fn get_branch_summary(&self, id: BranchId) -> Result<Option<BranchSummary>>;

    /// Check if Branch exists
    async fn branch_exists(&self, id: BranchId) -> Result<bool>;

    /// Get Company by ID
    async fn get_company(&self, id: CompanyId) -> Result<Option<CompanyDto>>;

    /// Get Company summary by ID
    async fn get_company_summary(&self, id: CompanyId) -> Result<Option<CompanySummary>>;

    /// Check if Company exists
    async fn company_exists(&self, id: CompanyId) -> Result<bool>;

    /// Get CompanyIndustry by ID
    async fn get_company_industry(&self, id: CompanyIndustryId) -> Result<Option<CompanyIndustryDto>>;

    /// Get CompanyIndustry summary by ID
    async fn get_company_industry_summary(&self, id: CompanyIndustryId) -> Result<Option<CompanyIndustrySummary>>;

    /// Check if CompanyIndustry exists
    async fn company_industry_exists(&self, id: CompanyIndustryId) -> Result<bool>;

    /// Get Department by ID
    async fn get_department(&self, id: DepartmentId) -> Result<Option<DepartmentDto>>;

    /// Get Department summary by ID
    async fn get_department_summary(&self, id: DepartmentId) -> Result<Option<DepartmentSummary>>;

    /// Check if Department exists
    async fn department_exists(&self, id: DepartmentId) -> Result<bool>;

    /// Get Industry by ID
    async fn get_industry(&self, id: IndustryId) -> Result<Option<IndustryDto>>;

    /// Get Industry summary by ID
    async fn get_industry_summary(&self, id: IndustryId) -> Result<Option<IndustrySummary>>;

    /// Check if Industry exists
    async fn industry_exists(&self, id: IndustryId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of OrganizationQueryService
pub struct OrganizationQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> OrganizationQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
