//! Public types for Organization module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use crate::domain::entity::*;

// ============================================================================
// BRANCH TYPES
// ============================================================================

/// Type-safe ID for Branch
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BranchId(pub Uuid);

impl BranchId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for BranchId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<BranchId> for Uuid {
    fn from(id: BranchId) -> Self {
        id.0
    }
}

/// Data transfer object for Branch
///
/// This is the public representation of Branch for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BranchDto {
    pub id: BranchId,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub branch_type: BranchType,
    pub is_head_office: bool,
    pub npwp: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub address: Option<String>,
    pub city: Option<String>,
    pub province: Option<String>,
    pub postal_code: Option<String>,
    pub country: String,
    pub status: OrgStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of Branch for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BranchSummary {
    pub id: BranchId,
    pub name: String,
    pub email: Option<String>,
    pub status: OrgStatus,
}

/// Reference to Branch for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BranchRef {
    pub id: BranchId,
}

// ============================================================================
// COMPANY TYPES
// ============================================================================

/// Type-safe ID for Company
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CompanyId(pub Uuid);

impl CompanyId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CompanyId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CompanyId> for Uuid {
    fn from(id: CompanyId) -> Self {
        id.0
    }
}

/// Data transfer object for Company
///
/// This is the public representation of Company for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompanyDto {
    pub id: CompanyId,
    pub code: String,
    pub legal_name: String,
    pub trade_name: Option<String>,
    pub npwp: Option<String>,
    pub nib: Option<String>,
    pub entity_type: CompanyEntityType,
    pub base_currency: String,
    pub fiscal_year_start_month: i32,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub address: Option<String>,
    pub city: Option<String>,
    pub province: Option<String>,
    pub postal_code: Option<String>,
    pub country: String,
    pub parent_company_id: Option<Uuid>,
    pub is_default: bool,
    pub status: CompanyStatus,
    pub notes: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of Company for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompanySummary {
    pub id: CompanyId,
    pub legal_name: String,
    pub trade_name: Option<String>,
    pub email: Option<String>,
    pub status: CompanyStatus,
}

/// Reference to Company for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompanyRef {
    pub id: CompanyId,
}

// ============================================================================
// COMPANYINDUSTRY TYPES
// ============================================================================

/// Type-safe ID for CompanyIndustry
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CompanyIndustryId(pub Uuid);

impl CompanyIndustryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CompanyIndustryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CompanyIndustryId> for Uuid {
    fn from(id: CompanyIndustryId) -> Self {
        id.0
    }
}

/// Data transfer object for CompanyIndustry
///
/// This is the public representation of CompanyIndustry for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompanyIndustryDto {
    pub id: CompanyIndustryId,
    pub company_id: Uuid,
    pub industry_id: Uuid,
    pub is_primary: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of CompanyIndustry for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompanyIndustrySummary {
    pub id: CompanyIndustryId,
}

/// Reference to CompanyIndustry for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompanyIndustryRef {
    pub id: CompanyIndustryId,
}

// ============================================================================
// DEPARTMENT TYPES
// ============================================================================

/// Type-safe ID for Department
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct DepartmentId(pub Uuid);

impl DepartmentId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for DepartmentId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<DepartmentId> for Uuid {
    fn from(id: DepartmentId) -> Self {
        id.0
    }
}

/// Data transfer object for Department
///
/// This is the public representation of Department for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DepartmentDto {
    pub id: DepartmentId,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub parent_id: Option<Uuid>,
    pub level: i32,
    pub is_group: bool,
    pub branch_id: Option<Uuid>,
    pub manager_id: Option<Uuid>,
    pub sort_order: i32,
    pub status: OrgStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of Department for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DepartmentSummary {
    pub id: DepartmentId,
    pub name: String,
    pub status: OrgStatus,
}

/// Reference to Department for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DepartmentRef {
    pub id: DepartmentId,
}

// ============================================================================
// INDUSTRY TYPES
// ============================================================================

/// Type-safe ID for Industry
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct IndustryId(pub Uuid);

impl IndustryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for IndustryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<IndustryId> for Uuid {
    fn from(id: IndustryId) -> Self {
        id.0
    }
}

/// Data transfer object for Industry
///
/// This is the public representation of Industry for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IndustryDto {
    pub id: IndustryId,
    pub code: String,
    pub name: String,
    pub sector: KBLISector,
    pub parent_id: Option<Uuid>,
    pub status: OrgStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of Industry for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IndustrySummary {
    pub id: IndustryId,
    pub name: String,
    pub status: OrgStatus,
}

/// Reference to Industry for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IndustryRef {
    pub id: IndustryId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
