//! Organization Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::BranchService;
pub use application::service::CompanyService;
pub use application::service::CompanyIndustryService;
pub use application::service::DepartmentService;
pub use application::service::IndustryService;

// <<< CUSTOM
pub use application::service::{
    validate_npwp, NewBranch, NewDepartment, OnboardError, OnboardRequest, OnboardResult,
    OnboardingService, OrgWriteError, OrgWriteService, HierarchyService,
};
pub use presentation::http::{
    create_guarded_organization_routes, create_guarded_organization_routes_checked,
    create_hierarchy_routes, create_onboarding_routes, create_organization_routes,
    require_known_company,
};
// END CUSTOM
// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Organization module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let organization = OrganizationModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = organization.all_crud_routes();
/// ```
pub struct OrganizationModule {
    pub branch_service: Arc<BranchService>,
    pub company_service: Arc<CompanyService>,
    pub company_industry_service: Arc<CompanyIndustryService>,
    pub department_service: Arc<DepartmentService>,
    pub industry_service: Arc<IndustryService>,
    // <<< CUSTOM
    /// Atomic company onboarding (Company + head-office Branch in one transaction).
    pub onboarding_service: Arc<OnboardingService>,
    /// Validated Branch/Department writes (NPWP format, same-company parent/branch, no cycle).
    pub org_write_service: Arc<OrgWriteService>,
    /// Company operational hierarchy read (Company → Branches → Departments tree).
    pub hierarchy_service: Arc<HierarchyService>,
    // END CUSTOM
}

impl OrganizationModule {
    /// Create a new module builder
    pub fn builder() -> OrganizationModuleBuilder {
        OrganizationModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_branch_routes,
            create_company_routes,
            create_company_industry_routes,
            create_department_routes,
            create_industry_routes,
        };

        Router::new()
            .merge(create_branch_routes(self.branch_service.clone()))
            .merge(create_company_routes(self.company_service.clone()))
            .merge(create_company_industry_routes(self.company_industry_service.clone()))
            .merge(create_department_routes(self.department_service.clone()))
            .merge(create_industry_routes(self.industry_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for OrganizationModule
pub struct OrganizationModuleBuilder {
    db_pool: Option<PgPool>,
}

impl OrganizationModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<OrganizationModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Branch service
        let branch_repository = Arc::new(BranchRepository::new(db_pool.clone()));
        let branch_service = Arc::new(BranchService::with_repository(branch_repository.clone()));

        // Company service
        let company_repository = Arc::new(CompanyRepository::new(db_pool.clone()));
        let company_service = Arc::new(CompanyService::with_repository(company_repository.clone()));

        // CompanyIndustry service
        let company_industry_repository = Arc::new(CompanyIndustryRepository::new(db_pool.clone()));
        let company_industry_service = Arc::new(CompanyIndustryService::with_repository(company_industry_repository.clone()));

        // Department service
        let department_repository = Arc::new(DepartmentRepository::new(db_pool.clone()));
        let department_service = Arc::new(DepartmentService::with_repository(department_repository.clone()));

        // Industry service
        let industry_repository = Arc::new(IndustryRepository::new(db_pool.clone()));
        let industry_service = Arc::new(IndustryService::with_repository(industry_repository.clone()));

        // <<< CUSTOM
        let onboarding_service = Arc::new(OnboardingService::new(db_pool.clone()));
        let org_write_service = Arc::new(OrgWriteService::new(db_pool.clone()));
        let hierarchy_service = Arc::new(HierarchyService::new(db_pool.clone()));
        // END CUSTOM

        Ok(OrganizationModule {
            branch_service,
            company_service,
            company_industry_service,
            department_service,
            industry_service,
            // <<< CUSTOM
            onboarding_service,
            org_write_service,
            hierarchy_service,
            // END CUSTOM
        })
    }
}

impl Default for OrganizationModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}