//! Use case type aliases for Branch aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateBranchDto, UpdateBranchDto};
use crate::application::service::BranchService;
use crate::domain::entity::Branch;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateBranchUseCase = CreateUseCase<Branch, CreateBranchDto, BranchService>;
pub type UpdateBranchUseCase = UpdateUseCase<Branch, UpdateBranchDto, BranchService>;
pub type GetBranchUseCase    = GetUseCase<Branch, BranchService>;
pub type DeleteBranchUseCase = DeleteUseCase<Branch, BranchService>;
pub type ListBranchUseCase   = ListUseCase<Branch, BranchService>;

// <<< CUSTOM
// END CUSTOM
