//! Use case type aliases for Company aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCompanyDto, UpdateCompanyDto};
use crate::application::service::CompanyService;
use crate::domain::entity::Company;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCompanyUseCase = CreateUseCase<Company, CreateCompanyDto, CompanyService>;
pub type UpdateCompanyUseCase = UpdateUseCase<Company, UpdateCompanyDto, CompanyService>;
pub type GetCompanyUseCase    = GetUseCase<Company, CompanyService>;
pub type DeleteCompanyUseCase = DeleteUseCase<Company, CompanyService>;
pub type ListCompanyUseCase   = ListUseCase<Company, CompanyService>;

// <<< CUSTOM
// END CUSTOM
