//! Use case type aliases for Department aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateDepartmentDto, UpdateDepartmentDto};
use crate::application::service::DepartmentService;
use crate::domain::entity::Department;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateDepartmentUseCase = CreateUseCase<Department, CreateDepartmentDto, DepartmentService>;
pub type UpdateDepartmentUseCase = UpdateUseCase<Department, UpdateDepartmentDto, DepartmentService>;
pub type GetDepartmentUseCase    = GetUseCase<Department, DepartmentService>;
pub type DeleteDepartmentUseCase = DeleteUseCase<Department, DepartmentService>;
pub type ListDepartmentUseCase   = ListUseCase<Department, DepartmentService>;

// <<< CUSTOM
// END CUSTOM
