//! Use case type aliases for Level aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateLevelDto, UpdateLevelDto};
use crate::application::service::LevelService;
use crate::domain::entity::Level;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateLevelUseCase = CreateUseCase<Level, CreateLevelDto, LevelService>;
pub type UpdateLevelUseCase = UpdateUseCase<Level, UpdateLevelDto, LevelService>;
pub type GetLevelUseCase    = GetUseCase<Level, LevelService>;
pub type DeleteLevelUseCase = DeleteUseCase<Level, LevelService>;
pub type ListLevelUseCase   = ListUseCase<Level, LevelService>;

// <<< CUSTOM
// END CUSTOM
