//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod branch_usecases;
pub mod company_usecases;
pub mod department_usecases;

pub use branch_usecases::{
    CreateBranchUseCase, UpdateBranchUseCase, GetBranchUseCase,
    DeleteBranchUseCase, ListBranchUseCase,
};
pub use company_usecases::{
    CreateCompanyUseCase, UpdateCompanyUseCase, GetCompanyUseCase,
    DeleteCompanyUseCase, ListCompanyUseCase,
};
pub use department_usecases::{
    CreateDepartmentUseCase, UpdateDepartmentUseCase, GetDepartmentUseCase,
    DeleteDepartmentUseCase, ListDepartmentUseCase,
};

// <<< CUSTOM
// END CUSTOM
