//! Use case type aliases for Position aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePositionDto, UpdatePositionDto};
use crate::application::service::PositionService;
use crate::domain::entity::Position;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePositionUseCase = CreateUseCase<Position, CreatePositionDto, PositionService>;
pub type UpdatePositionUseCase = UpdateUseCase<Position, UpdatePositionDto, PositionService>;
pub type GetPositionUseCase    = GetUseCase<Position, PositionService>;
pub type DeletePositionUseCase = DeleteUseCase<Position, PositionService>;
pub type ListPositionUseCase   = ListUseCase<Position, PositionService>;

// <<< CUSTOM
// END CUSTOM
