//! Use case type aliases for Structure aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateStructureDto, UpdateStructureDto};
use crate::application::service::StructureService;
use crate::domain::entity::Structure;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateStructureUseCase = CreateUseCase<Structure, CreateStructureDto, StructureService>;
pub type UpdateStructureUseCase = UpdateUseCase<Structure, UpdateStructureDto, StructureService>;
pub type GetStructureUseCase    = GetUseCase<Structure, StructureService>;
pub type DeleteStructureUseCase = DeleteUseCase<Structure, StructureService>;
pub type ListStructureUseCase   = ListUseCase<Structure, StructureService>;

// <<< CUSTOM
// END CUSTOM
