//! HTTP handlers
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod branch_handler;
pub mod company_handler;
pub mod department_handler;

// <<< CUSTOM
pub mod onboarding_handler;
pub mod guarded_routes;
// END CUSTOM

// Re-exports
pub use branch_handler::{create_branch_routes, create_branch_read_routes, create_branch_write_routes};
pub use company_handler::{create_company_routes, create_company_read_routes, create_company_write_routes};
pub use department_handler::{create_department_routes, create_department_read_routes, create_department_write_routes};
// <<< CUSTOM
pub use onboarding_handler::{create_onboarding_routes, create_organization_routes};
pub use guarded_routes::create_guarded_organization_routes;
// END CUSTOM